### ISSUE TITLE
ads.cnn.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#10]
maybe keep this for now we will do more tests

**Comment by mitchellkrogza** [comment]
@xxcriticxx still included at L>406258 of latest hosts file. I removed it earlier today as a dupe from another source. Keep testing and let me know how it goes and if you find any more false positives / additions. I added a new data source: https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/tree/master/.input_sources/_xxxcritic and you can now add new bad / porn sites you find to the domains.txt file there and send Pull Requests.
