### ISSUE TITLE
discovery.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#105]
i only see half of the page i whistelisted all from chrome and still no go

**Comment by xxcriticxx** [comment]
@mitchellkrogza can you please look in to this for me

**Comment by mitchellkrogza** [comment]
Have you got the latest version of this list?

I added quite a few domains they use.

**Comment by xxcriticxx** [comment]
let me check and i let you know

**Comment by xxcriticxx** [comment]
something still blocking sign in option pressing sign in page loads in circles

**Comment by xxcriticxx** [comment]
i found the culprit EasyPrivacy list blocking login script

**Comment by mitchellkrogza** [comment]
👍  so it's not on my lists then ? Can I close this?

**Comment by xxcriticxx** [comment]
yes
