### ISSUE TITLE
gearbest.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#113]
::: /etc/pihole/list.7.hosts-file.net.domains (2 results)
127.0.0.1	gearbest.com
127.0.0.1	www.gearbest.com

this could per user add

**Comment by mitchellkrogza** [comment]
Fixed in: https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/c1eb5242ef50e43ee632b454fd89ec2801f5ea34
