### ISSUE TITLE
tinyurl.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#114]
Match found in list.41.hosts.ubuntu101.co.za.domains:
   j.tinyurl.com
   www.tinyurl.com

**Comment by mitchellkrogza** [comment]
Fixed in: https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/c1eb5242ef50e43ee632b454fd89ec2801f5ea34
