### ISSUE TITLE
Most frequently asked domain names

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#124]
https://support.umbrella.com/hc/en-us/articles/115007472907-Most-frequently-asked-domain-names-which-would-not-load-after-bypassing-or-in-White-List-Only-mode

**Comment by sanjayen** [comment]
@xxcriticxx How does one allow these domains without getting tracked? Are there any surrogate scripts similar to NoScript's Google Analytics one?

**Comment by xxcriticxx** [comment]
@sanjayen pihole or notrack

if they don't track you am sure someone else will :)

**Comment by sanjayen** [comment]
@xxcriticxx :) care to share the link for notrack?

**Comment by xxcriticxx** [comment]
https://github.com/quidsup/notrack
