### ISSUE TITLE
zajefajna.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#125]
Match found in list.41.hosts.ubuntu101.co.za.domains:
   zajefajna.com

polish warez site

**Comment by mitchellkrogza** [comment]
Should maybe have this as a local bypass on your system instead

**Comment by mitchellkrogza** [comment]
@xxcriticxx Happy New Year to you, wish you all the best for 2018 🎉

**Comment by xxcriticxx** [comment]
yes sure no problem please close it
