### ISSUE TITLE
newyork.cbslocal.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#135]
also back on the list :( 

Match found in list.41.hosts.ubuntu101.co.za.domains:
   newyork.cbslocal.com

**Comment by mitchellkrogza** [comment]
Sorry @xxcriticxx I saw now they did not get removed due to a failure in the Central whitelisting repo we use, will be addressed today.

**Comment by mitchellkrogza** [comment]
@xxcriticxx should be off now with latest build
