### ISSUE TITLE
iowa.gov

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#141]
we thank you for blocking state of Iowa

 Match found in list.41.hosts.ubuntu101.co.za.domains:
   ankenyiowa.gov
   cdn.ankenyiowa.gov
   cdn.crestoniowa.gov
   cdn.dallascountyiowa.gov
   cdn.doublecheckiowa.gov
   cdn.educateiowa.gov
   cdn.gearupiowa.gov
   cdn.grangeriowa.gov
   cdn.grimesiowa.gov
   cdn.grinnelliowa.gov
   cdn.healthyiowa.gov
   cdn.homebaseiowa.gov
   cdn.ihaveaplaniowa.gov
   cdn.ijobsiowa.gov
   cdn.indianolaiowa.gov
   cdn.investsmartiowa.gov
   cdn.iowa.gov
   cdn.knoxvilleiowa.gov
   cdn.leclaireiowa.gov
   cdn.licensediniowa.gov
   cdn.maharishivediccity-iowa.gov
   cdn.muscatineiowa.gov
   cdn.polkcountyiowa.gov
   cdn.scottcountyiowa.gov
   cdn.storycountyiowa.gov
   cdn.tamacountyiowa.gov
   cdn.teachiowa.gov
   cdn.therightcalliowa.gov
   cdn.winnebagocountyiowa.gov
   crestoniowa.gov
   dallascountyiowa.gov
   doublecheckiowa.gov
   educateiowa.gov
   gearupiowa.gov
   grangeriowa.gov
   grimesiowa.gov
   grinnelliowa.gov
   healthyiowa.gov
   homebaseiowa.gov
   ihaveaplaniowa.gov
   ijobsiowa.gov
   indianolaiowa.gov
   investsmartiowa.gov
   iowa.gov
   knoxvilleiowa.gov
   leclaireiowa.gov
   licensediniowa.gov
   maharishivediccity-iowa.gov
   muscatineiowa.gov

**Comment by mitchellkrogza** [comment]
Will sort this tomorrow, will also find which source list this came from as it may be proving to be an unreliable data source.
