### ISSUE TITLE
ohio.gov

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#142]
+5 extra for this 

this has more results btw

Exact match for ohio.gov found in:
   list.41.hosts.ubuntu101.co.za.domains

**Comment by mitchellkrogza** [comment]
Wow, I must check from which list that crept in from.

**Comment by mitchellkrogza** [comment]
These all seem to emanate from - https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/.input_sources/_HOSTS_AdBlock/domains.txt @funilrys
