### ISSUE TITLE
oregon.gov

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#153]

**Comment by mitchellkrogza** [comment]
See - https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/.input_sources/_HOSTS_AdBlock/domains.txt ... seems we do have an unreliable input source. Might be worth also contacting the list owner on this, I think for now this entire input source will be dropped from this list.

**Comment by xxcriticxx** [comment]
looks like he dont like .gov websites

**Comment by mitchellkrogza** [comment]
The daily automated build is currently in progress, soon as it finishes I will push a commit to resolve this all. Stand by.

**Comment by xxcriticxx** [comment]
thank you

**Comment by mitchellkrogza** [comment]
Build in progress wait 10 minutes and new version will be out.

**Comment by mitchellkrogza** [comment]
@xxcriticxx test now and you should see all those gone, please confirm. Will address other remaining issues  tomorrow, thanks for reporting this.

**Comment by xxcriticxx** [comment]
did you pull whole list? if not i recommend looking on whole .gov because there is much more
