### ISSUE TITLE
surveymonkey.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#157]
Match found in list.41.hosts.ubuntu101.co.za.domains:
   aide.surveymonkey.com
   api.surveymonkey.com
   asdf.surveymonkey.com
   assets01.surveymonkey.com
   audience.surveymonkey.com
   blog.surveymonkey.com
   br.blog.surveymonkey.com
   ch.surveymonkey.com
   contribute.surveymonkey.com
   cxmx.surveymonkey.com
   da.surveymonkey.com
   de.surveymonkey.com
   developer.surveymonkey.com
   dk.surveymonkey.com
   en.surveymonkey.com
   es.surveymonkey.com
   fi.surveymonkey.com
   fr.surveymonkey.com
   go2.surveymonkey.com
   google.surveymonkey.com
   go.surveymonkey.com
   help.surveymonkey.com
   hilfe.surveymonkey.com
   htwww.surveymonkey.com
   ie.surveymonkey.com
   images.surveymonkey.com
   it.surveymonkey.com
   jp.blog.surveymonkey.com
   jp.surveymonkey.com
   ko.surveymonkey.com
   kr.surveymonkey.com
   lang-de.surveymonkey.com
   lang-ko.surveymonkey.com
   lang-pt.surveymonkey.com
   mail.surveymonkey.com
   mta04.sjc.surveymonkey.com
   mta05.sjc.surveymonkey.com
   mta07.sjc.surveymonkey.com
   mta09.sjc.surveymonkey.com
   mta10.sjc.surveymonkey.com
   nl.surveymonkey.com
   no.surveymonkey.com
   omp.go.surveymonkey.com
   omptrans.go.surveymonkey.com
   ondersteuning.surveymonkey.com
   p.t.surveymonkey.com
   pt.surveymonkey.com
   ru.surveymonkey.com
   sales.surveymonkey.com
   Over 50 results found, skipping rest of file

**Comment by funilrys** [comment]
I can't find `surveymonkey.com` into the new system.

Closing.
