### ISSUE TITLE
 patrz.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#158]
short films/music/yt style website

Match found in list.41.hosts.ubuntu101.co.za.domains:
   ocen.moj.tyleczek.patrz.pl
   patrz.pl
   sexy.jaime.hammer.patrz.pl
   sexy.lady.ponownie.patrz.pl
   sexypanie.patrz.pl
   shay.laren.sexy.patrz.pl

**Comment by funilrys** [comment]
@xxcriticxx Most of those comes from the respectable http://www.shallalist.de/ I'm not sure this is wrong ...

__________________________
# Search result

```
./Airelles_Anti_Sex_Hosts/domains.list:patrz.pl
./www.shallalist.de/domains.list:ocen.moj.tyleczek.patrz.pl
./www.shallalist.de/domains.list:patrz.pl
./www.shallalist.de/domains.list:sexy.jaime.hammer.patrz.pl
./www.shallalist.de/domains.list:sexy.lady.ponownie.patrz.pl
./www.shallalist.de/domains.list:sexypanie.patrz.pl
./www.shallalist.de/domains.list:shay.laren.sexy.patrz.pl
```

**Comment by xxcriticxx** [comment]
@funilrys links redirect to adult entertainment :)

Warning!

The materials on this site contain content marked as adults only. Do you want to enable showing these materials?

**Comment by funilrys** [comment]
@xxcriticxx I finally decided to allow only `patrz.pl` as the other one are redirections.
