### ISSUE TITLE
wiadomosci.onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#159]
part of onet.pl 

Onet.pl is the largest Polish web portal. It is owned by the Kraków-based Grupa Onet.pl S.A. It was founded in 1996 by Optimus company. According to Alexa rankings, as of October 2017, it was the 45th most popular website worldwide and the 3rd most popular site in Poland.

Match found in list.41.hosts.ubuntu101.co.za.domains:
   wiadomosci.onet.pl

**Comment by funilrys** [comment]
Looks legitimate @mitchellkrogza @xxcriticxx 

We are restructuring the project/repository, please be patient :+1:  

Thanks for your awesome work :+1: :100:

**Comment by xxcriticxx** [comment]
@funilrys i am not in rush thank you for your great software and thx to @mitchellkrogza for hosting this file

**Comment by funilrys** [comment]
Just a notice for the future @xxcriticxx, 

Because of the new structure, you can now send a PR to https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/master/domains.list and we will review/pull :+1:

**Comment by funilrys** [comment]
I can't find `wiadomosci.onet.pl` into the new system.

Closing.
