### ISSUE TITLE
videolan.org

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#160]
found by @Eva850 at pl filters repo

 Match found in list.41.hosts.ubuntu101.co.za.domains:
   www.videolan.org

**Comment by funilrys** [comment]
As this domain is not present into the comming infrastructure ([cf](https://github.com/search?utf8=%E2%9C%93&q=org%3AUltimate-Hosts-Blacklist+filename%3Adomains.list+videolan.org&type=Code)) 

closing.

**Comment by funilrys** [comment]
Closing as added to https://github.com/Ultimate-Hosts-Blacklist/whitelist/commit/c0ad815816019e771002cd221dbbedc61051a2f1 have to write the code to whitelist it but this can be closed.

Closing.
