### ISSUE TITLE
gratka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#162]
classified ads buy/sell

Match found in list.41.hosts.ubuntu101.co.za.domains:
   ale-gratka.pl
   gratka.pl

**Comment by funilrys** [comment]
Seriously !? How can I whitelist something or someone who presents itself as the following? 

From [here](https://pl.wikipedia.org/wiki/Gratka.pl) : 
> gratka.pl is one of the largest advertising services in Poland

@mitchellkrogza must approve this but I do not caution advertising services... So @mitchellkrogza please decide ...

**Comment by funilrys** [comment]
Maybe I misunderstood @xxcriticxx please let me know if it's the case as I do not live in Poland ... Is this a ebay like ? :thinking:

**Comment by xxcriticxx** [comment]
More like Craig’s list I just want know that it’s a legit website
