### ISSUE TITLE
wirtualnemedia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#165]
Match found in list.34.hosts.ubuntu101.co.za.domains:
   wirtualnemedia.pl

probably has the word advertising so it got canned same as gratka.pl

Virtual Media - Polish information portal devoted to television, radio, press, internet, advertising, technology, public relations and marketing research.

The portal was founded on December 1, 2001. He is visited by over 500,000 people a month. users. The information published on the portal is published on the largest websites (including Onet.pl, Wirtualna Polska, Interia.pl) and newspapers (including "Rzeczpospolita", "Gazeta Wyborcza", "Dziennik", Fakt "," Super Express, "Press", "Newsweek") [2].

Currently, the editor-in-chief of the portal is Marcin Szumichora [3]

**Comment by funilrys** [comment]
Also into shallalist.
