### ISSUE TITLE
tampermonkey.net

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#167]
Match found in list.34.hosts.ubuntu101.co.za.domains:
   tampermonkey.net

**Comment by funilrys** [comment]
Already in the whitelist https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/efbc06a93bb12db6b1ecf1ba2b2a265665275d58/domains.list#L205 

We are facing an issue with the auto-updater because of the big size of the repository ... I'm working on the fix :+1: 

Closing.
