### ISSUE TITLE
my qnap nas

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#172]
i think we have bad list

![1cc7847e-1259-4e1a-a9cc-2d8cc5f2e90f](https://user-images.githubusercontent.com/15007183/37549204-33af4c3c-2954-11e8-91cb-16ba34fc9242.jpeg)

**Comment by funilrys** [comment]
Well, it's only a matter of whitelisting.

As you may see I look at all your reports here and reviewed them one by one so all your reported domains are whitelisted ...

So I do not understand that. I'm not a Mac user but this only looks like an information ... Will search all occurrence of apple to see if one of them is "vital".

**Comment by funilrys** [comment]
@mitchellkrogza any opinion on this? :thinking:

**Comment by xxcriticxx** [comment]
@funilrys hold off on this i dont think is list related
