### ISSUE TITLE
internet stores

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#178]
sklep = store

i dont know if there is point blocking websites stores. am sure you find ads and banners there but thats the nature of internet store.

what is your opinion on this matter?

Match found in list.34.hosts.ubuntu101.co.za.domains:
   admansklep.pl
   alpinizm.sklep.pl
   artdeco.sklep.pl
   artsklep.pl
   asklep.pl
   asklepieio.gr
   asklepios-versand.de
   asklepios.com
   asklepios.it
   atb.sklep.pl
   autosklep.com.pl
   autosklep.istore.pl
   bass-sklep.pl
   bdsklep.pl
   bilard-sklep.pl
   bobosklep.pl
   brokat.sklep.pl
   candelluxsklep.pl
   cdsklep.pl
   cybersklep.com
   cynamonowo.super.sklep.pl
   dziecko.sklep.pl
   erosklep.pl
   eureka.sklep.pl
   ford.sklep.pl
   fotosklep.com.pl
   galeria.sklep.pl
   gsmsklep.abc24.pl
   infosklepy.pl
   internetowy-sklep.net
   isklep.net
   jubiler.sklep.pl
   kada.sklep.pl
   kami.sklep.pl
   ke.super.sklep.pl
   klimasklep.pl
   koncept.sklep.pl
   kosmetyki.isklep.pl
   kosmetykisklep.pl
   koszule.sklep.pl
   krasnal.sklep.pl
   krzesla-sklep.pl
   ksiazki.sklep.pl
   led.intersklep.pl
   magicznysklep.pl
   materace.sklep.pl
   modele.sklep.pl
   mojeauto.sklep.pl
   moto.sklep.pl
   musicland.sklep.pl
   narzedziownia.sklep.pl
   pgk.sklep.pl
   piloty-sklep.com.pl
   prosklep.com
   puzzle-sklep.pl
   rowerowysklep.com
   rtvagd.sklep.pl
   sex-sklep.com.pl
   sex-sklep.pl
   sexshop-sklep.pl
   sexshopsklep.boo.pl
   shift.sklep.pl
   sklep-agd.com.pl
   sklep-agnes.pl
   sklep-gercio.pl
   sklep-intymny.pl
   sklep-med.pl
   sklep-okon.pl
   sklep-tytoniowy.abc24.pl
   sklep-uv.pl
   sklep-wedkarski.com.pl
   sklep.abad.pl
   sklep.abaks.lublin.pl
   sklep.agaton.pl
   sklep.agrochlopecki.pl
   sklep.akutech.pl
   sklep.and1.pl
   sklep.anti.pl
   sklep.arcus.com.pl
   sklep.arpb.pl
   sklep.astrohobby.pl
   sklep.audiolite.pl
   sklep.avans.pl
   sklep.avt.com.pl
   sklep.b-52.com.pl
   sklep.bas-com.pl
   sklep.bast.pl
   sklep.bergo.pl
   sklep.bestfilm.pl
   sklep.bio-med.pl
   sklep.bodycenter.pl
   sklep.celiakia.pl
   sklep.coffea.pl
   sklep.cytadela.pl
   sklep.de-ka.net
   sklep.dil.pl
   sklep.drewno.pl
   sklep.e-street.pl
   sklep.eduforum.pl
   sklep.eldrut.pl
   sklep.elestra.pl
   sklep.era.pl
   sklep.eris.pl
   sklep.fbb.pl
   sklep.fotomatwij.com.pl
   sklep.galla.pl
   sklep.gastromer.pl
   sklep.gazeta.pl
   sklep.grabieniec.pl
   sklep.gral.pl
   sklep.hanwag.pl
   sklep.henderson.pl
   sklep.henwar.pl
   sklep.hip-hop.pl
   sklep.ibg.pl
   sklep.infor.pl
   sklep.insgraf.pl
   sklep.internetowydom.pl
   sklep.ipsip.pl
   sklep.jerk.pl
   sklep.komputronik.pl
   sklep.krasnoludki.pl
   sklep.kswiking.pl
   sklep.ladyga.pl
   sklep.lexpolonica.pl
   sklep.linux.pl
   sklep.logos.pl
   sklep.lupoline.pl
   sklep.maipa.pl
   sklep.matech.pl
   sklep.medyna.pl
   sklep.monpol.pl
   sklep.mular.pl
   sklep.mzuri.pl
   sklep.namuche.pl
   sklep.net-kom.pl
   sklep.nowaera.com.pl
   sklep.oczkowodne.net
   sklep.officemedia.pl
   sklep.optimeks.com.pl
   sklep.phumaria.pl
   sklep.plusgsm.pl
   sklep.portalfk.pl
   sklep.programatory.com
   sklep.pryzmet.pl
   sklep.q.pl
   sklep.romstom.pl
   sklep.rybieoko.pl
   sklep.sail-ho.pl
   sklep.scandinavia.net.pl
   sklep.semigat.pl
   sklep.sevenet.pl
   sklep.si.net.pl
   sklep.so.net.pl
   sklep.strongman.org.pl
   sklep.tadar.com.pl
   sklep.tarotnet.pl
   sklep.teta.pl
   sklep.tewati.net
   sklep.tomi2.com.pl
   sklep.trimed.pl
   sklep.tuning.pl
   sklep.unimetal.pl
   sklep.vena-vita.wkrakowie.net
   sklep.vgm.pl
   sklep.vilcacora.info.pl
   sklep.wittchen.pl
   sklep.zbymar.com.pl
   sklepamm.win.pl
   sklepandbud.pl
   sklepdatakom.pl
   sklepddd.ii.pl
   sklepdladziecka.pl
   sklepdlazwierzat.pl
   sklepfrk.pl
   sklepfryzjerski.pl
   sklephobby.pl
   sklepik.net.pl
   sklepik.unitel.krakow.pl
   sklepinternetowy.pl
   sklepit.pl
   sklepmeggy.pl
   sklepmikado.pl
   sklepmtg.abc24.pl
   sklepmuzyk.pl
   sklepnarzedziowy.pl
   sklepogrodnika.pl
   skleppc.pl
   sklepwgk.pl
   sklepwideo.pl
   sklepwindsurfingowy.pl
   sklepy24.pl
   sklepzeglarski.com
   sklepzeglarski.net
   twojesklepy.pl
   voip.sklep.pl
   wawel-sklep.com.pl
   wifi.sklep.pl
   www.asklepios-versand.de
   xcsklep.istore.pl
   zamex.sklep.pl
   zoologiczny.sklep.pl

**Comment by xxcriticxx** [comment]
nope but i could

can you check german webiste and let me know http://www.asklepios-versand.de/

**Comment by funilrys** [comment]
Okay then you may have a big problem ... Let me ping @mitchellkrogza  ...

___________________________________________
The following is the report I'm writing ... Not all domain checked but nothing in that list will be whitelisted soon.

`admansklep.pl` :negative_squared_cross_mark:
![bildschirmfoto vom 2018-03-18 13-03-32](https://user-images.githubusercontent.com/14127285/37565619-c885e0a6-2aac-11e8-8c6b-e7064545e09c.png)

`alpinizm.sklep.pl` :negative_squared_cross_mark: redirect to rockmaster.com.pl
`artdeco.sklep.pl` :negative_squared_cross_mark: This one is really strange ... I don't feel confident navigating on this one ...
`artsklep.pl` :negative_squared_cross_mark:
![bildschirmfoto vom 2018-03-18 13-08-21](https://user-images.githubusercontent.com/14127285/37565661-7c215622-2aad-11e8-9e82-e4305e2772ef.png)

`asklep.pl|asklepieio.gr|asklepios.com|candelluxsklep.pl|cybersklep.com|cynamonowo.super.sklep.pl|internetowy-sklep.net|ke.super.sklep.pl` :negative_squared_cross_mark: it redirects to many links that are blocked by well-known lists like the one maintained by Steven Black.

`asklepios-versand.de` :negative_squared_cross_mark: it redirects to `shopssl.de` when wanting to buy something which is also blocked by well-known lists like the one maintained by Steven Black.

`asklepios.it` :negative_squared_cross_mark:
![bildschirmfoto vom 2018-03-18 13-27-07](https://user-images.githubusercontent.com/14127285/37565784-123326b6-2ab0-11e8-8992-86bc7220400f.png)

`atb.sklep.pl` :negative_squared_cross_mark: nothing to buy there ... really strange ...

`autosklep.com.pl` :negative_squared_cross_mark:
![bildschirmfoto vom 2018-03-18 13-56-52](https://user-images.githubusercontent.com/14127285/37566061-437caaae-2ab4-11e8-95d7-bd6fb18f3270.png)

`autosklep.istore.pl` :negative_squared_cross_mark: I did not know that UPS had so unprofessional agents
![strange pic](https://autosklep.istore.pl/userdata/boxes/4354b32d3ac8fd70000cebd4544a9764.jpg)

`bass-sklep.pl|kami.sklep.pl` :negative_squared_cross_mark: How can it be so unprofessional by proposing amount transfert as only "payment method" ...

`bdsklep.pl` :crossed_fingers: Need further look but I'm not excluding it at all cause it is in a middle of a list of s**t websites ...

`bilard-sklep.pl` :red_circle: :negative_squared_cross_mark:  Force you to go to `bilardsklep.pl` **will/should be blocked somewhere** ... :red_circle:

`bobosklep.pl` :negative_squared_cross_mark: Nothing to buy ...

`brokat.sklep.pl` :negative_squared_cross_mark:
![bildschirmfoto vom 2018-03-18 14-27-33](https://user-images.githubusercontent.com/14127285/37566376-85fd10b8-2ab8-11e8-8cab-640cdf71fe44.png)

`cdsklep.pl` :negative_squared_cross_mark: How can it be so unprofessionalby not proposing one of the most known payement wall method.

`dziecko.sklep.pl` :negative_squared_cross_mark: Nothing to see.

`erosklep.pl` :negative_squared_cross_mark: Not funny but give us a list of link to block

`eureka.sklep.pl` :negative_squared_cross_mark: Error 502

`ford.sklep.pl` :negative_squared_cross_mark: Try to be serious but images are not saying that it is serious

`fotosklep.com.pl` :negative_squared_cross_mark: Nothing to see ...
![bildschirmfoto vom 2018-03-18 14-40-38](https://user-images.githubusercontent.com/14127285/37566501-58fb1162-2aba-11e8-9712-7314ccdb3d06.png)

`galeria.sklep.pl` :negative_squared_cross_mark: I do not need a reason for whitelisting this ...

`gsmsklep.abc24.pl` :negative_squared_cross_mark: I will not provide image here but what a trap ...

`infosklepy.pl` :negative_squared_cross_mark: does not look great to be taken as serious ...

`isklep.net` :negative_squared_cross_mark: I'll try to call their number to see ...

`jubiler.sklep.pl` :negative_squared_cross_mark: unprofessional

`kada.sklep.pl`:negative_squared_cross_mark: nothing to buy ...

**Comment by xxcriticxx** [comment]
ok now i know why they are on the list

**Comment by mitchellkrogza** [comment]
None of these look in any way professional or the kind of store anyone would risk actually giving their credit card info to and possibly very bad if they did. @xxcriticxx  how are you picking up all of these off your pi-hole?

**Comment by xxcriticxx** [comment]
@mitchellkrogza what you mean?

**Comment by mitchellkrogza** [comment]
@xxcriticxx I mean are you detecting these in your pi-hole logs as forbidden outgoing connections from your home network?

**Comment by xxcriticxx** [comment]
how i am finding all false positives?

**Comment by mitchellkrogza** [comment]
Yes

**Comment by xxcriticxx** [comment]
my luck i guess i use your list daily

**Comment by mitchellkrogza** [comment]
Ok I get that but are these false positives showing up in your pi-hole log files daily as being blocked from being accessed ?

**Comment by xxcriticxx** [comment]
am sure if @funilrys gives me german word for store we will find few in my pihole list 

btw did you remove sonos and twitter yet?

**Comment by xxcriticxx** [comment]
@mitchellkrogza no i visit websites and if its blocked i check my pihole lists why

**Comment by mitchellkrogza** [comment]
Ok just trying to establish where the false positive data is coming from, some of those .pl stores that @funilrys has checked through today look fishy

**Comment by xxcriticxx** [comment]
@funilrys said they come from some well know german list that you used from start

**Comment by mitchellkrogza** [comment]
Ahhh okay now we are on the same page.

**Comment by funilrys** [comment]
Yes, all are into `www.shallalist.de` @mitchellkrogza

**Comment by xxcriticxx** [comment]
i also have terminal open that shows me what gets blocked live i dont know if this helps you

![screenshot from 2018-03-18 10-11-42](https://user-images.githubusercontent.com/15007183/37566873-43bce746-2a95-11e8-88d2-8c449696c896.png)

**Comment by mitchellkrogza** [comment]
One of those .pl sites I visited threw up this warning for me 

![aaa](https://user-images.githubusercontent.com/9961541/37566903-f87e2cf8-2ac7-11e8-9ab4-ede43614df84.PNG)

**Comment by mitchellkrogza** [comment]
@xxcriticxx thanks that does help us, are you able to tell what site you visited that threw up all the "sklep" sites in your list. Do your log files go back to that point? just interested to see if you maybe visited one web site that triggered all of those to be blocked

**Comment by xxcriticxx** [comment]
had to be list something that was on the list

**Comment by funilrys** [comment]
Closing, feel free to reopen if needed @mitchellkrogza
