### ISSUE TITLE
invalid domain

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#186]
this is back see #143 

Mar 20 04:51:00 dnsmasq[25346]: bad name at /etc/pihole/gravity.list line 1979164

huala\F1e.cl

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx we are still fine tuning things with the new layout, sure @funilrys can sort this out in our functions

**Comment by funilrys** [comment]
Hello there @mitchellkrogza, 

PyFunceble already handles that when we get a `clean.list` which is not the case of `www.shallalist.de` ([cf](https://travis-ci.org/mitchellkrogza/Ultimate.Hosts.Blacklist/builds/355621765#L543)) for the reason we both know.

However, our search script was not able to locate where does `huala\F1e.cl` comes from. 

So the questions are: 

- [ ] are you sure we are talking about this repository? 
- [ ] Is `/etc/pihole/gravity.list` referencing to another list?

**Comment by xxcriticxx** [comment]
correct boys its not on this list

it shows up on `hosts-file.net` do we use this list?

@funilrys `/etc/pihole/gravity.list` thats the list from my pihole where all lists merge together

**Comment by funilrys** [comment]
@xxcriticxx I hope that one day girls will be here to discuss with us so let's avoid `boys` :wink: 

No we are not using it in this list (yet or forever? :thinking:)

Closing.
