### ISSUE TITLE
jebzdzidy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#2]
this website shows funny pictures why is blacklisted?

**Comment by mitchellkrogza** [comment]
Keep logging these issues and I will fix when I am back in office. Keep in
mind that a new hosts list and needs lots of refinement still.

**Comment by funilrys** [comment]
He may be on holiday so you're gonna get an answer at least at the end of the next week :wink:

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/fcaa791f48194829bd090e8a15d87bb4de6b0e1d
