### ISSUE TITLE
List Culling and Sorting (WIP)

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Ultimate.Hosts.Blacklist#20]
Work in progress, major sorting of input source lists splitting IP's and domain names into separate lists and removing thousands of duplicates. 

Should be done by day end and will make managing of this repo much easier from here on out. 

A lot of the input sources have VERY bad duplications and structures using full urls including url parameters and file names which are actually totally useless inside a hosts file as are IP addresses which now only get generated into the hosts.deny and superhosts.deny files.

**Comment by funilrys** [comment]
:+1: You gave me the idea of URL implementation into funceble but it's may be for the future ... :) 

By the way, I'm almost ready for the next release :wink: 
https://github.com/funilrys/funceble/issues/91 ==> You gonna like it :stuck_out_tongue_winking_eye:

**Comment by xxcriticxx** [comment]
this is how pihole does it 

https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists

**Comment by mitchellkrogza** [comment]
Thanks @xxriticxx and @funlirys I have custom scripts to do this all but it does take time and cross checking. Almost done and you can see the list has shrunk somewhat. By tomorrow morning it will be in a really nice clean state going forward. @xxcriticxx I also found some other false positives during this process today.

**Comment by xxcriticxx** [comment]
@mitchellkrogza will the list be smaller in size(mb) wise?

**Comment by mitchellkrogza** [comment]
Yes indeed, it will be smaller and quicker to update once all the dupes are truly gone.

**Comment by xxcriticxx** [comment]
yes right now its around 60mb should be around 5mb only 

why do you have `ALL` in front of everything?

**Comment by mitchellkrogza** [comment]
For your pihole you should be pulling the latest hosts raw file and not
hosts.deny or superhosts.dent

**Comment by xxcriticxx** [comment]
so i think i am pulling wrong list i only need ip or domains

**Comment by xxcriticxx** [comment]
please give me link to correct list

**Comment by mitchellkrogza** [comment]
https://hosts.ubuntu101.co.za/hosts

**Comment by xxcriticxx** [comment]
i will play with it later on today

**Comment by mitchellkrogza** [comment]
Lists all sorted and clean now, been quite a job.
Fixed In: https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/9816d45d8f1bc10a8a56271c799580c5910898d0

**Comment by funilrys** [comment]
looks really good @mitchellkrogza :+1: good work :100:

**Comment by mitchellkrogza** [comment]
Thanks @funilrys 👍  it's now the way it should be. The hosts file contains only domains and not IP addresses as that's the way it should actually be for the way DNS works. IP's are now all listed in the hosts.deny file so the combination of using the hosts + hosts.deny on any "nix" system should keep out 99% of utter garbage 👍

**Comment by mitchellkrogza** [comment]
Now to run the new funceble when it's out against these lists 😬  but I'll do that from my Ubuntu box and not inside Travis

**Comment by funilrys** [comment]
You should wait a bit :wink: :sweat_smile: 
I did a lot of refactoring/rewriting so the next version will be 2.0.0 :smile_cat: :wink: :stuck_out_tongue_winking_eye:

**Comment by mitchellkrogza** [comment]
@xxcriticxx the raw hosts file at https://hosts.ubuntu101.co.za/hosts is now down to 54Mb. It's nice and clean now and will get even cleaner once I run it against funceble and strip out all dead and inactive domains but at least now it's a proper hosts file with domain names only and not IP addresses as it should be. So as explained above to @funilrys if you use the hosts + hosts.deny on any nix system you will be well protected.

**Comment by mitchellkrogza** [comment]
@funilrys no worries, I'm in no rush, I would rather wait until you have perfected it. Going to be massively interesting to see the results when I do get to run it against this list. Once funceble can help clean out all dead and expired domains this should be the squeakiest clean list out there.

**Comment by funilrys** [comment]
I personally can't wait to see if you find some issues :wink: :joy_cat: 

I hope that https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/9816d45d8f1bc10a8a56271c799580c5910898d0/.input_sources/_urlblacklist.com/spyware/ips.txt will help me improve the handle of IP 

Just discovered that https://github.com/funilrys/funceble/issues/83 is not as fixed as I thought :sob:

**Comment by xxcriticxx** [comment]
```
::: Getting hosts.ubuntu101.co.za list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: 
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 2798632 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 2181269 unique domains trapped in the event horizon.
```

**Comment by mitchellkrogza** [comment]
@xxcriticxx Please Pull it again now and repost your report, just updated it again as there was a problem with some duplications which I fixed now. V1.2017.08.109

**Comment by mitchellkrogza** [comment]
@funilrys if you look in all the directories in .input_sources you will see what work I did yesterday splitting domains and ips into separate files. Lots of IP's to test now at: 465,685

**Comment by xxcriticxx** [comment]
```
::: Getting hosts.ubuntu101.co.za list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: 
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 2758639 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 2181269 unique domains trapped in the event horizon.
```

pihole will take care of duplication

**Comment by mitchellkrogza** [comment]
Perfect thanks @xxcriticxx let me know if you find any more false positives.

**Comment by mitchellkrogza** [comment]
@xxcriticxx raw hosts file now down to 52 Mb.

**Comment by funilrys** [comment]
@mitchellkrogza I saw it :wink: https://github.com/funilrys/funceble/issues/83 is now officially fixed :+1:

**Comment by xxcriticxx** [comment]
@mitchellkrogza are you going to add any more list in to it?

@funilrys congratulations!

**Comment by mitchellkrogza** [comment]
@funilrys awesome, will run a test on it now. I created two very simple plain text lists in this repo now. One is a list of all domains only and the other a list of all IP's.

https://hosts.ubuntu101.co.za/domains.list
https://hosts.ubuntu101.co.za/ips.list

@xxcriticxx it will keep growing all the time as it pulls fresh data from certain sources everytime I run a build. Once I have funceble run through it it should reduce down in size again because then I can remove all dead, expired and inactive domains from the list.

**Comment by funilrys** [comment]
@mitchellkrogza it's in the dev branch until I'm done with refactoring :+1:

**Comment by mitchellkrogza** [comment]
👍  cool I cloned the dev repo and I set it loose on https://hosts.ubuntu101.co.za/domains.list 😀  will post output when it's done.

**Comment by mitchellkrogza** [comment]
🤣  I can see this one is going to take some time to complete

**Comment by mitchellkrogza** [comment]
And we have lift off with http response codes ..... @funilrys well done !!!!! 🥇 

![screen shot 2017-08-17 at 2 21 02 pm](https://user-images.githubusercontent.com/9961541/29412072-89256ca8-8357-11e7-9f22-6453e0d433f5.png)

**Comment by funilrys** [comment]
Looks good :trophy: 

But the 04-jul-7123 is quite impossible :joy_cat: :joy_cat:

**Comment by mitchellkrogza** [comment]
I guess some whois servers are just broken and run by idiots ...... trust me a good 70% of the world's DNS and even registry's are in the hands of utter morons with a piece of paper on the wall that says they are clever. Now to take the response codes one step further ..... (perhaps a separate project altogether) .... to run a redirect checker tool against a list already cleaned by funceble and then run it on that list and actually record all the 302 redirects of a domain until it eventually gets to to a final 200 OK ..... this would be the ultimate malware finder.

**Comment by funilrys** [comment]
Interesting I had the same idea since I started with `httpCode()` :joy_cat:

**Comment by funilrys** [comment]
And for that issue it's a code side issue :D 

whois return `Domain Expiration Date:                      Sun Jul 15 23:59:59 GMT 2018`

**Comment by mitchellkrogza** [comment]
Thats' what I need ...... I have to track bad sites manually using screen recorder on OSX as some of them do 3-10 redirects in the blink of an eye.

Who knows maybe that guy who registered 0000opengate.biz thought he might live to be 5200 years old 🤣

**Comment by mitchellkrogza** [comment]
Does that mean Mitch uncovered another 🐛  😁 

whois return Domain Expiration Date: Sun Jul 15 23:59:59 GMT 2018

**Comment by funilrys** [comment]
> Does that mean Mitch uncovered another :bug:  :grin:

Definitely :joy_cat: :+1:

**Comment by mitchellkrogza** [comment]
By the way found a really cool one liner yesterday to clean lists. Both lists have to be sorted and dupe free .... works very well but ..... knowing you, you will find and even cleverer way just to outwit me 🤣 

`comm -13 funceble-inactive.txt domains.txt >> domains.sorted`

**Comment by mitchellkrogza** [comment]
This is how far it's got in 25 minutes 😬  ..... this is going to take till tomorrow morning.

![screen shot 2017-08-17 at 2 39 49 pm](https://user-images.githubusercontent.com/9961541/29412698-1f730ee8-835a-11e7-8f57-5478828fc5f5.png)

**Comment by mitchellkrogza** [comment]
@xxcriticxx I can see once I remove all these dead and inactive domains I will have my Ultimate hosts down to a much more respectable size for all users and also only filled with stuff that actually exists.

**Comment by mitchellkrogza** [comment]
@funilrys I tell you one thing, and this was why I started Ultimate Hosts .... 90% of the lists out there are filled with utterly useless garbage that does not exist anymore and nobody cleans or bothers to clean their lists.

**Comment by xxcriticxx** [comment]
@mitchellkrogza how many hosts can dnsmasq handle?

**Comment by mitchellkrogza** [comment]
@xxcriticxx really not sure, don't use it. Try asking on their forums.

**Comment by mitchellkrogza** [comment]
@funilrys think I'm going to pull the new dev funceble into Badd-Boyz-Hosts and let it loose tonight. See if I can beat the Travis 50 minute timeout.

**Comment by xxcriticxx** [comment]
@mitchellkrogza thats what pihole using for the hosts i know it has to have limit

**Comment by mitchellkrogza** [comment]
@xxcriticxx does your pi-hole ever crash with my list size ???

**Comment by mitchellkrogza** [comment]
@xxcriticxx trying to find out for you.

**Comment by mitchellkrogza** [comment]
@xxcriticxx please see: https://discourse.pi-hole.net/t/does-pi-hole-have-a-limit-on-the-number-of-hosts/4518

**Comment by xxcriticxx** [comment]
@mitchellkrogza did not crash yet but i am running it on reg computer not pie3

**Comment by mitchellkrogza** [comment]
Try it and see what happens, only way to find out. Remember once my funceble output of this list finishes, probably by tomorrow morning sometime there will be a LOT of dead stuff culled out of this hosts list.

**Comment by xxcriticxx** [comment]
@mitchellkrogza check this webiste out see if you can add any lists https://filterlists.com/

**Comment by mitchellkrogza** [comment]
Nice find @xxcriticxx I'll add some of these in the morning. Thanks for
your support on this project.

**Comment by mitchellkrogza** [comment]
@xxcriticxx added 4 new data sources today so far, so thanks for that link 👍 . Some of them look well maintained, some of them not so much. Also some are useless to a hosts file. 

But we are slowly growing this into a really top notch list and once @funilrys finishes his work on the dev branch of funceble we will clean this list of all dead and useless stuff and then have a killer accurate hosts list barre none.

**Comment by mitchellkrogza** [comment]
@xxcriticxx added 6 new data sources today, more tomorrow then over the weekend once funceble finishes checking there will be a big clean up of dead domains.

**Comment by xxcriticxx** [comment]
@mitchellkrogza is my list good to pull?

**Comment by mitchellkrogza** [comment]
@xxcriticxx which one ?? Please point me to it.

**Comment by mitchellkrogza** [comment]
Added another new data source today, pre-edited version of someonewhocares.org

**Comment by xxcriticxx** [comment]
@mitchellkrogza did you update raw list that i use can i pull new list?

**Comment by mitchellkrogza** [comment]
@xxcriticxx raw lists always up to date immediately after a build completes.

**Comment by mitchellkrogza** [comment]
@xxcriticxx just wait 5 minutes, busy with new build and fresh files in 5 minutes

**Comment by mitchellkrogza** [comment]
@xxcriticxx all raw files at latest version.

**Comment by xxcriticxx** [comment]
ok i will pull later when am home

**Comment by mitchellkrogza** [comment]
Cool let me know, also see if you know anyone who can test the windows version of the hosts file. It seems ok on XP but does require that DNS client is disabled
