### ISSUE TITLE
Manage Windows 10 connection endpoints

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#201]
https://docs.microsoft.com/en-us/windows/configuration/manage-windows-endpoints-version-1709

**Comment by funilrys** [comment]
Thanks @xxcriticxx :+1: 
What do you think about it? Addition or whitelisting? As those can be in both sides :smile_cat:

**Comment by xxcriticxx** [comment]
first lets see what we have on the list and how critical they are
