### ISSUE TITLE
Windows (DOS/CRLF) formatted hosts file (TESTING NEEDED)

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Ultimate.Hosts.Blacklist#21]
@funilrys @xxcriticxx any chance either of you have a Windows PC to test this out? 

I tested it in a Windows 7 VM (VMWare), seems to work fine but need someone to test it on a real windows PC.

https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/update-hosts-windows.bat

**Comment by funilrys** [comment]
I'm on Arch Linux :smile: but I may have a windows box in the basement or the attic :joy_cat:

**Comment by mitchellkrogza** [comment]
Testing it now on an old Acer Laptop with Windows XP. Will let you know if it works OK.

**Comment by xxcriticxx** [comment]
does it work with 2mil host on xp?

**Comment by mitchellkrogza** [comment]
NOPE, does not seem to like it AT ALL 😬  That's windows for you eh? 🤣

**Comment by xxcriticxx** [comment]
@mitchellkrogza i dotn know why they want to disable dns client service but this what i found on quick google search 

Windows DNS Client Service

In most cases the DNS Client Service is not needed, it is recommended to turn it off. These instructions are intended for a single (home-user) PC. If your machine is part of a "Domain", check with your IT Dept. before applying this work-around. This especially applies to Laptop users who travel or bring their work machines home. Make sure to reset the Service (if needed) prior to connecting (reboot required) to your work Domain ...

To resolve this issue (manually) open the "Services Editor"

    Start | Run (type) "services.msc" (no quotes)
    Win8 users - Control Panel > Administrative Tools > Services
    Scroll down to "DNS Client", Right-click and select: Properties - click Stop
    Click the drop-down arrow for "Startup type"
    Select: Manual (recommended) or Disabled  click Apply/Ok and restart.

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx I will try that out and report back. My poor old 10 year old Acer laptop is taking some serious strain with that hosts file 🤣 🤣

**Comment by xxcriticxx** [comment]
make sure you dont kill it

**Comment by mitchellkrogza** [comment]
I've got a fire extinguisher on stand by 😬

**Comment by xxcriticxx** [comment]
it would best if you test outdoors

**Comment by mitchellkrogza** [comment]
🤣

**Comment by mitchellkrogza** [comment]
@xxcriticxx it works. Disabled DSN Client. It can do nslookups and pings now. Slow to respond on pings due to the large file BUT considering this old laptop only has 4gb of ram a 10 second delay before it starts pinging is not too bad.

```
Pinging 105vibe.com [0.0.0.0] with 32 bytes of data:

Destination specified is invalid.
Destination specified is invalid.
Destination specified is invalid.
Destination specified is invalid.

Ping statistics for 0.0.0.0:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

```

**Comment by xxcriticxx** [comment]
how many people now days use xp? i think you should test 7 and up

**Comment by mitchellkrogza** [comment]
Pushed out a new version for Windows using 127.0.0.1 as the loopback instead of 0.0.0.0 will see if that makes any difference.

**Comment by mitchellkrogza** [comment]
Tested and working on Windows XP 100% 😮  Can you believe it. 
Windows does not seem to like the 0.0.0.0 addressing, certainly not XP or Windows7. 
But yes it works even at 2,458,916 entries and on a 10 year old Acer laptop 👍
