### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#215]
probably others

gry.wp.pl
kontakt.wp.pl
poczta.wp.pl
pogoda.wp.pl
sport.wp.pl
wiadomosci.wp.pl

**Comment by funilrys** [comment]
- `gry.wp.pl`
- `gry.wp.pl`
- `gry.wp.pl`
- `gry.wp.pl`
- `gry.wp.pl`

**Comment by funilrys** [comment]
- `gry.wp.pl`
    * I do not know what to think about this.
- `kontakt.wp.pl`
    * Redirects to `profil.wp.pl`
- `poczta.wp.pl`
    * Redirects to `profil.wp.pl`
- `pogoda.wp.pl`
    * I do not know what to think about this.
- `sport.wp.pl`
    * Redirects to `sportowefakty.wp.pl`
- `wiadomosci.wp.pl`
    * That one looks strange :thinking: 

We are not ready to whitelist those @xxcriticxx sorry.

**Comment by xxcriticxx** [comment]
@funilrys https://en.wikipedia.org/wiki/Wirtualna_Polska
