### ISSUE TITLE
tvnplayer.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#217]
Match found in list.34.hosts.ubuntu101.co.za.domains:
   tvnplayer.pl

**Comment by funilrys** [comment]
Redirect to `tvnplayer.pl`.

Closing.

**Comment by xxcriticxx** [comment]
@funilrys player.pl is top website in poland for vod

this from wiki

The previous name of TVN Player
Website
Player (formerly: TVN Player) - Polish online video service on demand and Internet TV. Since launch, he has been offering access to films, series and programs known from the channel offer from the TVN Group logo (TVN, TVN 7, TVN Style, TVN Turbo). In 2013, it was enriched with the content of vod channels TVN24, TVN Meteo, Religia.tv and TTV.

February 24, 2014 the name of the site has been changed to the current one and has been expanded with new functionalities. In addition to the vod content, the first live streaming channels (TVN24, TVN Meteo, TVN 24 Biznes and Świat, Mango 24) have been made available to it, as well as live content and content from external broadcasters: FilmBox Live package (FilmBox, FilmBox Extra, DocuBox HD , FashionBox HD, FightBox HD, Kino Polska, Kino Polska Muzyka) and AXN Now (AXN, AXN Black, AXN White, AXN Spin) [2].

The website is available on the internet via a web browser. In the form of an application it is also available on mobile devices, in TV sets on Smart TV platforms, STB digital television of various operators and on consoles.

Access to the site is free for users, however, advertisements appear when materials are broadcast. On February 24, 2014, the Player Plus package was released, access to which is payable.

August 31, 2017 Player changed its appearance and logo.

**Comment by xxcriticxx** [comment]
@funilrys  anything `tvn` in poland is mostly tv stations

**Comment by funilrys** [comment]
Please report to #222 then :+1:
