### ISSUE TITLE
Windows Testers

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Ultimate.Hosts.Blacklist#22]
Please can any windows users test the Windows version and also the install and update batch script and report back here. Many thanks.

**Comment by xxcriticxx** [comment]
link to test file please

**Comment by mitchellkrogza** [comment]
https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/update-hosts-windows.bat

**Comment by mitchellkrogza** [comment]
That's both an installer and updated script

**Comment by mitchellkrogza** [comment]
Latest hosts file tested on an old Windows XP machine and working 100% does require that DNS client service is disabled and name servers for network connection set manually to 8.8.8.8 and 8.8.4.4.... Can confirm this works and should work on all versions of Windows

**Comment by mitchellkrogza** [comment]
Any Windows 10 testers out there ?

**Comment by xxcriticxx** [comment]
Me this weekend if I don't forget

**Comment by mitchellkrogza** [comment]
@xxcriticxx awesome looking forward to the feedback.

**Comment by xxcriticxx** [comment]
@mitchellkrogza do you have uninstall script just in case?

**Comment by mitchellkrogza** [comment]
I'll add one into the repo now.

**Comment by mitchellkrogza** [comment]
This should do the trick  https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/uninstall-hosts-windows.bat

**Comment by mitchellkrogza** [comment]
@xxcriticxx replaced and modified setup and uninstall scripts for Windows

https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/windows-install-update-hosts.bat

https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/windows-uninstall-hosts.bat

**Comment by xxcriticxx** [comment]
@hawkeye116477 can you please test this on windows computer

**Comment by hawkeye116477** [comment]
@xxcriticxx Rather no, because I very rarely use Windows. Maybe @MajkiIT?

**Comment by xxcriticxx** [comment]
@hawkeye116477 maybe lets see if they show up over here

**Comment by MajkiIT** [comment]
@mitchellkrogza I tested this script and I see this alert https://www.screencast.com/t/zF15Fq3V . Of course I open CMD with Admin privileges.

**Comment by mitchellkrogza** [comment]
@hawkeye116477 thanks sorry I made a change in the install-update script, please pull latest version and try again.

**Comment by MajkiIT** [comment]
@mitchellkrogza this message is to me ?

**Comment by mitchellkrogza** [comment]
@MajkiIT I updated both https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/windows-install-update-hosts.bat and https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/windows-uninstall-hosts.bat today to fix some CRLF / DOS formatting issues. Please try with latest .bat scripts.

**Comment by MajkiIT** [comment]
@mitchellkrogza 
PC1 Win 7 Pro
Install https://www.screencast.com/t/jZ8cM4z7FH
uninstall https://www.screencast.com/t/4zdMmF370cl9

PC Win10 
Install https://www.screencast.com/t/N5cVRlG5V
Uninstall https://www.screencast.com/t/Aqi8qL6Bp

**Comment by mitchellkrogza** [comment]
So weird, I'm gonna have to try and tweak those scripts but I have no
Windows 8 or 10 machines. Will see if I can find any VM images on to
download to test.

**Comment by mitchellkrogza** [comment]
Funny though I tested this on windows 7 and it did work???

**Comment by xxcriticxx** [comment]
@MajkiIT is this on vm machine or real windows machine?

**Comment by xxcriticxx** [comment]
pc win7

install http://imgur.com/a/ynQWt
uninstall http://imgur.com/a/0c354

**Comment by mitchellkrogza** [comment]
@xxcriticxx so it worked??

**Comment by MajkiIT** [comment]
@xxcriticxx 
Win7 is VM
Win 10 i real

**Comment by xxcriticxx** [comment]
@mitchellkrogza i see errors in the install script

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx @MajkiIT I found the syntax error had a `”` instead of a `"`
Latest commit Fixes this > https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/8695f9f342e42d19b5cd1db981c5aca3f771af46

Busy testing on Windows 10 and it no longer has the syntax error issue.

**Comment by mitchellkrogza** [comment]
Tested using latest windows-install-update-hosts.bat on Windows 10 works 100%

**DOES require that DNS client is Disabled**

![screen shot 2017-08-27 at 4 41 59 pm](https://user-images.githubusercontent.com/9961541/29750823-068e7116-8b47-11e7-83cd-0a6178e1b751.png)

**DOES require that DNS Servers are specified in Network Connection Settings**

![screen shot 2017-08-27 at 4 44 43 pm](https://user-images.githubusercontent.com/9961541/29750836-34be0c68-8b47-11e7-8320-5733961e4b52.png)

**Results of pings**

![screen shot 2017-08-27 at 4 42 29 pm](https://user-images.githubusercontent.com/9961541/29750841-425440c2-8b47-11e7-8799-4610e2586af0.png)

**Comment by funilrys** [comment]
Disabling DNS client and enabling Google DNS server ? :thinking: 
I really can't understand windows :joy_cat: 

Need to document myself about that ...

**Comment by mitchellkrogza** [comment]
That's WinDOZE for you. 😹

**Comment by xxcriticxx** [comment]
@mitchellkrogza what happens when you leave dns on?

**Comment by mitchellkrogza** [comment]
Cannot ping anything or browse. can do DNS / nslookups but complete failure
on pinging or browsing.

Shows you how good their DNS client is even now in Windows 10 because the
same behavior is exhibited all the way back to Windows XP

**Comment by xxcriticxx** [comment]
i think windows has limit

**Comment by mitchellkrogza** [comment]
Apparently but not on any Linux or OSX system. As usual sterling good work for an operating you must still pay money for. But really I expect nothing less from Micro-sortof 

We have a major build in progress which is testing this entire hosts list, my calculations estimate it's going to take several days to complete but once it's done I reckon this list of domains will be stripped by almost half of all dead domains, non existent domains and lots of blogspot sites which all return 404 meaning they are long gone. 

The we will have a much more accurate and manageable list.

**Comment by xxcriticxx** [comment]
have to speed up script

**Comment by mitchellkrogza** [comment]
1,028,459 domains 
2 seconds per domain check

According to the last 24 hours (almost) of builds I estimate 9 days. 

If you work the above figures though it works out to 23 days. I reckon 8-9 days. Thank the lord the list is not the 3 million it was 2 weeks ago.

**Comment by mitchellkrogza** [comment]
@xxcriticxx according to latest stats we are averaging 4500 domain checks per 40 minute build. So the estimate of 9 days is pretty accurate.

**Comment by xxcriticxx** [comment]
@MajkiIT has somethign in php ask him to run your list

**Comment by mitchellkrogza** [comment]
Can you show me his proj. Doubt it could produce the reliable and solid output of funceble by @funilrys you can look through the builds in progress on this repo and the results of the checks. Truly solid and reliable information for list cleaning.

**Comment by xxcriticxx** [comment]
i haven't seen it my self we have to wait for him to show up

**Comment by funilrys** [comment]
@xxcriticxx Can't wait to see it :) Can it manage the PHP timeout?

**Comment by xxcriticxx** [comment]
@funilrys i dont code you can ask him 

@MajkiIT please report here

**Comment by MajkiIT** [comment]
Hi, I now try to run this project on .Net Core and PHP. I pay 2 developers to do it, because I'm not don't code. Now I have problem with blocking DNS request, by my ISP. So I build a DNS loadbalanser and roundrobin DNS requests by 10 servers. I think that on max 2 weeks I will end this.

**Comment by mitchellkrogza** [comment]
Go look at the commits on this project over the last 24 hours and then look in the.dev-tools/funceble/output/result.txt file

**Comment by mitchellkrogza** [comment]
Don't know what your project is about or what you are paying people for because for testing dead domains it's already done with all the work @funilrys has put into funceble.... With me constantly asking for new features LOL

**Comment by MajkiIT** [comment]
@mitchellkrogza I want to find dead domains. I want to learn something so I want to find best and fast way. I pay them about 20$ . I want to analyse code and it's all. Next releases I will do it.

**Comment by MajkiIT** [comment]
@mitchellkrogza I look for this file and It's ok, but you use whois but I think, that is limit od whois requests. Maybe better is use DNS request to find that domain is resolved.

**Comment by mitchellkrogza** [comment]
funceble does nslookups, whois checks and checks the page status 200, 301, 302, 404 etc and all in 2 seconds per domain. @funilrys

**Comment by mitchellkrogza** [comment]
Have a good and proper look at funceble @funilrys has put so much work into it and I've kept asking for features, kept finding bugs and it's now truly unbeatable

**Comment by MajkiIT** [comment]
@mitchellkrogza I know. I don't want to say that is bad IDEA. I think that it's very good work, but I want to find another solution. I try to use script on Linux and I have 10 domain per seconds.

**Comment by mitchellkrogza** [comment]
But you are getting blocked for too many lookups. You say 22 days and this cleaning output will be finished in 9 without being blocked.

**Comment by MajkiIT** [comment]
I was blocked because I push request to 1 server. I say 2 weeks, because developers will finish code. I tested 1800 domains in 2-3 minutes by linux script without ban.

**Comment by funilrys** [comment]
To stop the discussion and continue in a constructive way @MajkiIT can you give us a flowchart of your project(s)?

Here's the last of mine (many changes since then but it's really clear) ...
![global_funceble](https://user-images.githubusercontent.com/14127285/29789715-48ca9a32-8c37-11e7-9e5f-a70feb52968d.png)

**Comment by MajkiIT** [comment]
here is my bash script ==> https://github.com/MajkiIT/Work/blob/master/dead_domain.sh
The same solution I want to use in .Net Core and PHP.

**Comment by funilrys** [comment]
Well, we are at two different level then ... 
@mitchellkrogza are legitimate then because funceble is actually a level higher because it can handle false positive domains/subdomains ...

Did you pay someone for that? :scream:

**Comment by MajkiIT** [comment]
In my way I want find best way to dead domains. I run script ones a day and writes scores to file. 
No, I write this script in 2 minutes and I local solution. I want to .net or php to web app.

**Comment by xxcriticxx** [comment]
@MajkiIT thank you for showing up. i would like to introduce my two best friends :0

**Comment by funilrys** [comment]
Well, there's some limitation into PHP but it's not impossible ... Actually, Python will even be better than PHP or .net I think ... I don't know .net for now (gonna learn it if I come back to windows one day :joy_cat: )

To precise, I wrote it in bash/shell because I found that it'll be cool, I love Linux (especially Arch and Gentoo) and I wanted something that would be useful in a world that we have 1M line hosts file with only 500K  active ... 

And yeah I don't mind the time it takes the most accurate results only count for now :tongue: :joy_cat: 

But yeah it'll be interesting to see the PHP solutions :thinking:

**Comment by xxcriticxx** [comment]
@mitchellkrogza when is the next raw build coming?

**Comment by funilrys** [comment]
In a week @xxcriticxx :smile_cat:

**Comment by MajkiIT** [comment]
@funilrys but Linux scripts you run on server not by web /http/ . I want to do it be web page.

**Comment by xxcriticxx** [comment]
@funilrys list is good not i only found one false positive

**Comment by funilrys** [comment]
@MajkiIT I actually works not on a web app which would be impossible for 1 Million domains because of the PHP timeout but on https://github.com/funilrys/funceble/issues/62 which will come as a complement of funceble for deep analytic ... It's the only issue that is not implemented to the dev as it needs many times ...

But yeah it'll be interesting to have a web page or even better a GUI app which is one of my future projects :)

**Comment by xxcriticxx** [comment]
cool thx @funilrys

**Comment by MajkiIT** [comment]
@funilrys I want to run process on N servers, for example 5 . Divide the file by the number of servers and run 10 php process by server .

**Comment by funilrys** [comment]
Okay now I understand @xxcriticxx comment at https://github.com/funilrys/funceble/issues/90#issuecomment-318937573 :smile: For me it's not the solution but I don't have time to debate ... Gonna see what your developers produce if you put it on a repo. Otherwise Python can be used to create webapp too ... The world is not only around PHP ...

**Comment by mitchellkrogza** [comment]
@xxcriticxx @MajkiIT @xxcriticxx I'll start another thread regarding this.

Please let's keep this issue only for discussing Windows Testing.

**Comment by mitchellkrogza** [comment]
@xxcriticxx if you want daily updated lists of bad sites for now, just use 

https://github.com/mitchellkrogza/Badd-Boyz-Hosts
and
https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites

There will only be a new raw update on this list next week.

**Comment by xxcriticxx** [comment]
@mitchellkrogza once per week is ok with me just let me know when to pull

**Comment by mitchellkrogza** [comment]
@xxcriticxx I will most certainly update you all when the new RAW links are updated next week. Based on current stats when I push the update next week we will lose already 28% of dead domains from the list. I will monitor this daily.

**Comment by xxcriticxx** [comment]
@mitchellkrogza stop gettinggn high and back to work chop chop

**Comment by mitchellkrogza** [comment]
🤣 🤣 @xxcriticxx you know you are quite a slave driver, but I love it ...... always making sure you keep me on my toes

**Comment by xxcriticxx** [comment]
@mitchellkrogza thats how i know i have good list
