### ISSUE TITLE
kwejk.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#220]
Match found in list.34.hosts.ubuntu101.co.za.domains:
   kwejk.pl

**Comment by funilrys** [comment]
Because of the way it forces the users to disable adblocking system/extensions/software - between others - we are not whitelisting this.

Closing.

**Comment by xxcriticxx** [comment]
@funilrys many people use pihole + some type of ublock for element element hiding

**Comment by funilrys** [comment]
Well, @xxcriticxx, this is a decision we (@mitchellkrogza + @funilrys) took internally but we are open for discussions. 

I was surprised that this site can disable your Adblock extension for that site by clicking (link to xdg). 

Such liberty can go really wrong as we can not trust that website for such action in the future. Today it disables itself, tomorrow it will disable all its partners? 

We do not endorse that fact.
Such actions should be made by the user manually NEVER by a script or link (including xdg).

**Comment by xxcriticxx** [comment]
no problem
