### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#23]
0.0.0.0 google.com

**Comment by funilrys** [comment]
This one is a gold @mitchellkrogza  :+1: :100: :1st_place_medal: :joy_cat: :joy_cat: :joy_cat: :joy_cat:

**Comment by mitchellkrogza** [comment]
🤣  fixing now

**Comment by mitchellkrogza** [comment]
Should be fixed in: https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/5c0471265bffdcb05e95ed96420b5d87c16022fc

**Comment by mitchellkrogza** [comment]
RAW links updated

**Comment by mitchellkrogza** [comment]
@xxcriticxx let me know if you find anymore google or twitter links or Facebook. I've been doing lots of cleaning but obviously missed some. Please log all issues beginning with ADD: or REM: then it's easier for me to get through them

**Comment by funilrys** [comment]
@mitchellkrogza Hall of fame? :smile_cat:

**Comment by mitchellkrogza** [comment]
@funilrys absolutely
