### ISSUE TITLE
   lowes.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#230]
Match found in list.34.hosts.ubuntu101.co.za.domains:
   lowes.com

**Comment by funilrys** [comment]
I hope you agree with https://www.lowes.com/l/privacy-and-security-statement.html#interestadvertising :smile_cat:

**Comment by xxcriticxx** [comment]
@funilrys EasyPrivacy blocks this scripts
