### ISSUE TITLE
compare_ultimate

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#245]
@funilrys left you msg 7 days ago

**Comment by funilrys** [comment]
Sorry, I do not get notifications from Gist comments will look asap.

**Comment by funilrys** [comment]
Please take a look at https://gist.github.com/funilrys/900abd388b1f3b399a9da69e0e592fef#gistcomment-2411143 @xxcriticxx. 

Have a nice day/night.
