### ISSUE TITLE
real-debrid.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#268]
Match found in list.34.hosts.ubuntu101.co.za.domains:
   real-debrid.com

**Comment by xxcriticxx** [comment]
if you use kodi you use RD

i can whitelist this on my end if its problem

**Comment by funilrys** [comment]
@xxcriticxx It's waiting for a check which I will start asap so we will see :wink:  

P.s: Sorry for the waiting time.

**Comment by xxcriticxx** [comment]
no problem i already whitelisted on my end
