### ISSUE TITLE
samsung.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#27]
0.0.0.0 samsung.com

**Comment by mitchellkrogza** [comment]
Keep sending will have this all sorted tomo

**Comment by xxcriticxx** [comment]
Last list with zeros is kaka

**Comment by mitchellkrogza** [comment]
I think I am going to modify all lists to use 127.0.0.1 ??? What I think

**Comment by xxcriticxx** [comment]
makes no difference for me pihole will drop everything in front

**Comment by mitchellkrogza** [comment]
Been doing some reading yesterday and 127.0.0.1 (the original standard)
still seems best. Misconfigured systems (common) can easily have a problem
with the 0.0.0.0 ..... not sure who thought that up but seems all hosts
files have resorted to using it but saying that 90% of Hosts files out
there are not even tested by their creators
