### ISSUE TITLE
firsturl.de

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#270]
http://firsturl.de/02d38da?

@funilrys can you check its closer to your home 

this url let you download Jdownloader2

jdownloader Downloadserver #1 | Download 32/64Bit Webinstaller (Rar-Archive RECOMMENDED)

**Comment by xxcriticxx** [comment]
this is only redirect to mega.nz but then i found out my mega is block

**Comment by funilrys** [comment]
It does redirect me to https://mega.nz/#!DQUSDS4Q!3oCI6KwWTivL3PSTcTAv4YDQxKfkgxMEsehkdTLumP0  ...
