### ISSUE TITLE
*.tvp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#273]
this the full list of domains

Match found in list.34.hosts.ubuntu101.co.za.domains:
   bialystok.tvp.pl
   bydgoszcz.tvp.pl
   itvp.pl
   katowice.tvp.pl
   krakow.tvp.pl
   lodz.tvp.pl
   lublin.tvp.pl
   rzeszow.tvp.pl
   szczecin.tvp.pl
   tvp.pl
   vod.tvp.pl
   ww2.tvp.pl

**Comment by funilrys** [comment]
`itvp.pl` redirects to `tvp.pl` :negative_squared_cross_mark: 
`ww2.tvp.pl` redirects to `tvp.pl` :negative_squared_cross_mark:
