### ISSUE TITLE
ynet.co.il

### ISSUE THREAD

**Issue by elico** [mitchellkrogza/Ultimate.Hosts.Blacklist#276]
Ynet news\newspaper

Match found in list.34.hosts.ubuntu101.co.za.domains:
ynet.co.il

**Comment by funilrys** [comment]
It looks strange that it redirects me to https://www.ynet.co.il/home/0,7340,L-8,00.html ...

**Comment by elico** [comment]
@funilrys  where at:
- https://github.com/Ultimate-Hosts-Blacklist/adblock.mahakala.is/search?utf8=%E2%9C%93&q=ynet&type=

On what file?
And shallalist? for malware?
I can try to dig in it but it's a news site.
If stats is the issue then it something else but I think it should be first identified as a domains which either have malware or have stats all over it compared to one specific subdomain.

**Comment by funilrys** [comment]
@elico Please report to [GitHub documentation](https://developer.github.com/v3/search/#considerations-for-code-search): 

> Only files smaller than 384 KB are searchable.

We use our internal search script. 
A web app for deep searching will be available soon (I'm working on it as one of many side projects related to this repository).

# About our structure

* This repository compile all `clean.list` which are present in all input source repositories.
* This repository compile `domains.list` if `clean.list` is not present in the input source repository we are currently fetching.

**Comment by elico** [comment]
@funilrys I have a ready to use web dns and ICAP services which we can just use.
The update rate is 2M records update in less the 60 seconds and on a ATOM based machine it can take up to 3-4k requests per second no problems

**Comment by mitchellkrogza** [comment]
`It looks strange that it redirects me to https://www.ynet.co.il/home/0,7340,L-8,00.html ...`

That just looks like some really bad Microsoft IIS setup

**Comment by mitchellkrogza** [comment]
![capture](https://user-images.githubusercontent.com/9961541/39299868-14fd6dda-494a-11e8-86b7-32f870bbccfb.PNG)

This is probably why 2 lists have flagged the domain. ynet.co.il needs to review their ad policies for public display. I run a number of sites with ads and have them carefully setup not to display anything of a mature nature.

**Comment by mitchellkrogza** [comment]
![capture](https://user-images.githubusercontent.com/9961541/39300674-cefb6bd6-494c-11e8-9358-60c78912296c.PNG)

@elico not sure if you have any contact with the admin's of ynet, suggest they be contacted and told to review their adsense display policies under > Allow & Block Ads > Content > Sensitive Categories

**Comment by funilrys** [comment]
About the following:

> @funilrys I have a ready to use web dns and ICAP services which we can just use.
The update rate is 2M records update in less the 60 seconds and on a ATOM based machine it can take up to 3-4k requests per second no problems

That comment is out of the scope of this issue. 

Please start a new issue, a global or personal discussion so we can follow in our daily or weekly repositories/issues work.

Respectively:
* Global discussions about this repository :  [Slack](cybersecurity-crew.slack.com) 
* Personal discussions:
  * [Slack Private Messsage](cybersecurity-crew.slack.com) 
  * @mitchellkrogza
    * [KeyBase](https://keybase.io/mitchellkrog)
  * @funilrys
    * [KeyBase](https://keybase.io/funilrys)


--------------------

About this issue:

As @mitchellkrogza previously detailed, we are not whitelisting this (yet!?).

--------------------
Closing.

**Comment by elico** [comment]
ok will move where ever it fits later.(sorry for the long thread)
@mitchellkrogza I have not reviewed but I know they have adsense or something similar.
I will not contact their Admins since I don't really care... I just have seen people here using it daily for new so I was wondering.
I do know that *.ynet.co.il is being deeply censored for by the more "conservative" community here is Israel.

**Comment by mitchellkrogza** [comment]
Thanks @elico if we can get more clarity on ynet.co.il we would certainly review it again.

**Comment by elico** [comment]
@mitchellkrogza @funilrys The site itself has commercials but it's a local news site.
I do not like this site or it's methods and the commercials are probably there because of some JS which are fetching the adds from other sites and domains.
- mrb.upapi.net
- cdn.taboola.com
- ecdn.firstimpression.io
...

just load the page with adblock plus(developer tools open (F12)) and see what domains pops up that might be worth blocking.

Also I just wanted to clear out that I have here a local ISP which does very deep content filtering on these pages(to the JS level) due to these ads being present.
The news sites around the globe are just a step forward from the news industry of the old times.
These who are getting paid by the clients are not presenting these ads/commercials.
