### ISSUE TITLE
Mikrotik dns blacklisting domains

### ISSUE THREAD

**Issue by elico** [mitchellkrogza/Ultimate.Hosts.Blacklist#292]
I will create a script later but it's very simple to create a script that will also generate a mikrotik `rsc` script that adds blacklisted sites into their DNS service(which is something like dnsmasq.
the next should be in the rsc script:
```
/ip dns static
add address=146.112.61.104 name=sex.com comment="U.H-BL"
add address=146.112.61.104 name=www.sex.com comment="U.H-BL"
add address=146.112.61.104 name=porn.com comment="U.H-BL"
```
...
And it's very easy to flush these by a simple cleanup script.

Should I write the scripts?

**Comment by elico** [comment]
@funilrys I tried it and it seems that it will take above 22 hours to load the domains list into the dns service so..
No go for that but I will try to see if there is something else we can do.

**Comment by mitchellkrogza** [comment]
I've spent a bit of time with Mikrotik routers and from my experience the ability to implement security measures is cumbersome and clumsy. I think most Mikrotik routers would crash after the 22 hours simply because they don't have the memory to even deal with that amount of DNS entries.

**Comment by mitchellkrogza** [comment]
@elico any home router would be best off not being out under such strain and instead can just be simply configured to use our DNS for lookups. We refresh the DNS daily at 4pm, generating 3,5 million + records including wildcards and all of this in < 5 minutes
