### ISSUE TITLE
twitter.com images

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#310]
if you want to see images on twitter please whitelist:

`abs.twimg.com`
`pbs.twimg.com`

**Comment by funilrys** [comment]
@xxcriticxx Are you sure that those are on the list? 

I'm asking because we are whitelisting all `*.twimg` 

Cheers.

**Comment by xxcriticxx** [comment]
not on this list i think we already fixed that problem
