### ISSUE TITLE
small list

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#312]
did we drop hosts or lists? lists got smaller

**Comment by funilrys** [comment]
The explanation is that we finally distribute the cleaned (`clean.list`) version of [Ultimate-Hosts-Blacklist/www.shallalist.de](https://github.com/Ultimate-Hosts-Blacklist/www.shallalist.de).

Indeed, before PyFunceble finished the cleaning of the list 6 days ago, we were distributing the "messy" list (`domains.list`).

Thanks for asking.
Have a nice day/night.

---------------------------
Closing.

**Comment by mitchellkrogza** [comment]
@xxcriticxx it's taken a very long time but we can finally show how many dead domains there are on ShallaList thanks to @funilrys PyFunceble testing tool.
