### ISSUE TITLE
admiral domains

### ISSUE THREAD

**Issue by smed79** [mitchellkrogza/Ultimate.Hosts.Blacklist#319]
Find in the [attached file](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/files/2010440/admiral.txt) **admiral** tracking and anti adblock domains.

for `.input_sources/_SMed79/admiral/domains.txt`

(source https://forums.lanik.us/viewtopic.php?f=62&t=39468)

**Comment by funilrys** [comment]
Hi @smed79, 
As we updated our repository structure, all our input sources are now represented as repository into [Ultimate-Hosts-Blacklick](https://github.com/Ultimate-Hosts-Blacklist). 

Therefore, I invite you to join our team (already send the invitation) there so you can update your input sources yourself!

Have a nice day/night.
Cheers,
Nissar

____________________
Closing as every discussions around this input source should be now made from under the organisation.
