### ISSUE TITLE
   prnt.sc

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#320]
Match found in list.34.hosts.ubuntu101.co.za.domains:

   prnt.sc

**Comment by xxcriticxx** [comment]
same as https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/60

**Comment by funilrys** [comment]
The problem with this one is that it's listed into a list we are working on ... And being on that list is already a big warning for me that's why I have to check deeper the why it is on that alarming list.
