### ISSUE TITLE
observation

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#361]
i think you have something in your script that automatically strips the domain and adds it to the list. i find this very often in this list. for some reason stripped domain always make it to the list despite the fact that it is a valid website.

example:

Match found in list.34.hosts.ubuntu101.co.za.domains:
ads.abc.com
cdn.abc.com
my.abc.com
abc.com

**Comment by funilrys** [comment]
@xxcriticxx `abc.com` was not whitelisted so it's not a bug.

**Comment by funilrys** [comment]
Well, it's only mean that someone took some quality time to list all possible domain so you can enable only what you use! That exactly what we do no?

**Comment by xxcriticxx** [comment]
@funilrys nothing i thought you had something like this in your script

**Comment by funilrys** [comment]
@xxcriticxx No it's dependent from the input sources !
