### ISSUE TITLE
CoinBlockerLists

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#368]
cc @funilrys / @mitchellkrogza 

list moved to Gitlab

https://gitlab.com/ZeroDot1/CoinBlockerLists/

**Comment by funilrys** [comment]
Fixed by https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists/commit/cc18b8eb84358bc71caa4e29750c14cff25d69d8

Closing.
