### ISSUE TITLE
[false positive] bitbucket.org

### ISSUE THREAD

**Issue by dnmTX** [mitchellkrogza/Ultimate.Hosts.Blacklist#374]
Just a heads up guys. **bitbucket.org** is blocked in the latest malc0de update (crazy....i know).I asked ZeroDot1 to reach them on twitter to no avail.Very poor communications and support from their side.

**Comment by mitchellkrogza** [comment]
Thanks @dnmTX @funilrys will most certainly whitelist this before our next build takes place. Thanks for reporting

**Comment by dnmTX** [comment]
@mitchellkrogza  anytime 😎.I'll leave this open for @funilrys to see it,or you can close it if it doesn't need to be.

**Comment by mitchellkrogza** [comment]
No problem @dnmTX issue will be closed with the appropriate whitelist commit

**Comment by funilrys** [comment]
Hello there, It was already in the whitelist list!

**Comment by funilrys** [comment]
Reference: https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/9d991119677885215592a62977e7cb4636d9f139/domains.list#L61

**Comment by funilrys** [comment]
Already whitelisted.

____________
Closing.

**Comment by dnmTX** [comment]
@funilrys sorry,i didn't check your lists here before creating the issue,assumed that you guys didn't know yet.

**Comment by funilrys** [comment]
@dnmTX No problem :+1:
