### ISSUE TITLE
sympatia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#377]
dating portal

 Match found in list.34.hosts.ubuntu101.co.za.domains:
   sympatia.pl

**Comment by funilrys** [comment]
Not whitelisting because `sympatia.pl` redirects to `sympatia.onet.pl`.

 Closing.

**Comment by funilrys** [comment]
Note: Whitelisting was a mistake.
