### ISSUE TITLE
archive.ubuntu.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#39]
still not fixed

**Comment by funilrys** [comment]
#18 @mitchellkrogza

**Comment by mitchellkrogza** [comment]
Big fix coming this morning, only just woke up. Will address this all for good.

**Comment by mitchellkrogza** [comment]
@xxcriticxx I will also have some nice new raw links specially for your pi-hole which will be a plain text list of domains without any 0.0.0.0 or 127.0.0.1

**Comment by xxcriticxx** [comment]
@mitchellkrogza how was your beauty sleep princess?

**Comment by mitchellkrogza** [comment]
@xxcriticxx LOL ... indeed it was, didn't sleep the night before last night so only got up at 10am this morning 🤣

**Comment by xxcriticxx** [comment]
Stop by nyc you lucky if you get in 4 h in night
