### ISSUE TITLE
Big hosts file and Malwarebytes?

### ISSUE THREAD

**Issue by shkmaru** [mitchellkrogza/Ultimate.Hosts.Blacklist#398]
Since I got the windows big blocklist, Malwarebytes has been delayed on startup, hosts file is indelible and uneditable, and internet connection always shows "No connection" for both wired and wifi. 

Why does this happen and how can I fix it?

**Comment by xxcriticxx** [comment]
@shkmaru check if you have `www.msftncsi.com` and `dns.msftncsi.com` on your list

**Comment by mitchellkrogza** [comment]
@shkmaru have you looked at the suggestion from @xxcriticxx ? Please let us know.

**Comment by funilrys** [comment]
No response. Closing.
