### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#4]
Another big one

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/fcaa791f48194829bd090e8a15d87bb4de6b0e1d

**Comment by funilrys** [comment]
@mitchellkrogza Hall of fame? :smile_cat:

**Comment by mitchellkrogza** [comment]
@funilrys absolutely
