### ISSUE TITLE
gratka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#402]
Match found in list.34.hosts.ubuntu101.co.za.domains:

   gratka.pl

**Comment by funilrys** [comment]
@xxcriticxx May I know why you closed this ?

**Comment by xxcriticxx** [comment]
@funilrys duplicate of https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/162

**Comment by xxcriticxx** [comment]
somehow made it back to the list 

Match found in list.34.hosts.ubuntu101.co.za.domains:
   ads.gratka.pl
   ads.telemagazyn.gratka.pl
   gratka.pl
