### ISSUE TITLE
Proposal Cron Jobs instead of Installers

### ISSUE THREAD

**Issue by BerndHelber** [mitchellkrogza/Ultimate.Hosts.Blacklist#417]
Hello Mtchell, 

great Work as alays 
i would like to propose somethin.
Wouldn't it be a better Option to make i littbel bit more Use of cat and cron instead of moving Files.
In case some Application rely on the /etc/hosts File and might break if they will be overwritten.

 I'll try to point out what i 
Let#s assume we want to keep a Copy of the /etc/hosts file
In first place we create a Directory called

_`mkdir /etc/hosts.d/`_

The First Cron Job would start  at 22:59 we'll create a copy of our existing `/etc/hosts` File 

59 22 * * * cp  /etc/hosts /etc/hosts.bkp

Pulling the latest  Hosts list 11 PM

`0 23 * * * wget https://hosts.ubuntu101.co.za/hosts -O /etc/hosts.d/hostsblocked`

Copying the  Original /etc/hosts from /etc/hosts.d/hosts to /etc/hosts at 11PM and 10 Minutes

`10 23 * * * cp /etc/hosts.d/hosts  /etc/hosts`
Merging the Pulled  Hosts File which was called hostsblocked with the Servers Hosts File.  11PM and 12 Minutes

`12 23 * * * cat /etc/hosts.d/hostsblocked >> /etc/hosts
`
The Same kind of manner at example on the Hosts,deny
`59 4 * * * cp /etc/hosts.deny /etc/hosts.deny.bkp`
`0 5 * * * wget https://hosts.ubuntu101.co.za/superhosts.deny -O /etc/hosts.deny`

Wouldn't that be a proper Idea deploying the relevant Content and securing the existing Installation?

Kind regards

**Comment by mitchellkrogza** [comment]
Hi @BerndHelber I can't take all the credit @funilrys has done and continues to do amazing work and moderation of false positives not to mention the extensive and continuous testing for dead hosts with his amazing PyFunceble.

Wouldn't it be better thought to do something like this. 

A) backup hosts > hosts.bk
B) download new hosts > hosts.tmp
C) then simply in <1 sec mv hosts.tmp > hosts

Merging could cause incredibly big files with dupes to be created. Or am I not fully understanding you?

**Comment by BerndHelber** [comment]
Hi @mitchellkrogza you got my Intention completely right. :) 
I'm aware that it could cause big files, but that wouldn't be the case either.... cause only the regular `/etc/hosts` which is necessary for some crude applications would merge with the shiny new pulled Ultimate.Hosts.Blacklist. The Day from the last file would be held back for 24 Hours.

The idea to keep the initial /etc/hosts as fallback in a newly created directory called /etc/hosts.d/ was to have a fallback.

`/tmp `

for the Ultimate.Hosts.Blacklist. would also be a valid option.

Hopefully i was able to explain it a little bit better as before.

Take care and kind regards

**Comment by funilrys** [comment]
Well thanks for the credit @mitchellkrogza :+1:

I do not have that much time until the weekends, but I have to admit (as I use the hosts file in some cross machine environment) that I thought about creating a script (like the whitelisting one at https://github.com/Ultimate-Hosts-Blacklist/dev-center) which will let our user have a hosts file like:

```
#### Keep me ####
# Static table lookup for hostnames.
# See hosts(5) for details.
#127.0.0.1 localhost
#127.0.0.1 localhost.localdomain
#127.0.0.1 local
#255.255.255.255 broadcasthost
#::1 localhost ip6-localhost ip6-loopback
#fe80::1%lo0 localhost
#ff02::1 ip6-allnodes
#ff02::2 ip6-allrouters
#### Do not keep me ####
0.0.0.0 0.0.0.0
0.0.0.0 google.ocm
....
```

This way the merging will not be so painful ... What are your inputs on that ? Just let me know before I publish the script at https://github.com/Ultimate-Hosts-Blacklist/dev-center :smile_cat: 

Have a nice day/night!
Cheers, 
Nissar
