### ISSUE TITLE
security.debian.org

### ISSUE THREAD

**Issue by lightswitch05** [mitchellkrogza/Ultimate.Hosts.Blacklist#429]
According to [www.debian.org](https://www.debian.org/security/) the domain `security.debian.org` is used to supply security updates. 

    deb http://security.debian.org/debian-security stretch/updates main contrib non-free

Unless I'm not understanding this correctly, blocking this domain is a major security issue and goes directly against one of the project goals:

> protect your devices and pc from being infected with Malware or Ransomware. 

maybe this domain should be whitelisted?

**Comment by mitchellkrogza** [comment]
Hi @lightswitch05 thanks for reporting will get @funilrys to whitelist this asap. As we consolidate so many lists these do creep in and we will check which source mistakenly included that in their list.

**Comment by lightswitch05** [comment]
Thanks Mitchell. I figured it came from another list outside of this project. From a quick glace through the project, it wasn't immediate clear to me where the sources were defined for me to open an issue with the original creator

**Comment by mitchellkrogza** [comment]
@funilrys will be able to check which source. I haven't checked list in a while and just found a whole bunch of google domains that are blocked too.

**Comment by funilrys** [comment]
Hi @lightswitch05 thanks for reporting this.

It comes from 
```
www.shallalist.de/clean.list
```
So https://github.com/Ultimate-Hosts-Blacklist/www.blocklist.de.

Will add this to the whitelist list asap :+1:

**Comment by funilrys** [comment]
Oops @lightswitch05  wrong repo:

 We get it from 

```
www.shallalist.de/clean.list
```

which is our input source repository: https://github.com/Ultimate-Hosts-Blacklist/www.shallalist.de

**Comment by mitchellkrogza** [comment]
We shall one day 100% Clean that messy Shallalist
