### ISSUE TITLE
Repo Size: 2.8 Gb

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Ultimate.Hosts.Blacklist#44]
@xxcriticxx First fixing this rapidly growing repo size. 
Have it down now to almost < 200 Mb from 2.8 Gb.

Need to relook at fixing commits and cleaning history automatically of all .zip files during the build process.

Nearly done then will continue cleaning of all the false positives/

**Comment by xxcriticxx** [comment]
no more need for big files :)

**Comment by mitchellkrogza** [comment]
Already down from 2,458,966 hosts to 1,911,032 and busy with another commit now.

**Comment by mitchellkrogza** [comment]
And now down to 1,459,649

Now to go checking again for more of those false positives. Getting there slowly but surely

**Comment by mitchellkrogza** [comment]
@xxcriticxx okay this is where we stand now and things are looking better.

```
    Version: V1.2017.08.148
    Total Bad Hosts in hosts file: 1,030,677
    Total Bad Hosts in hosts.deny file: 275,519
    Total Bad Hosts and IP's in superhosts.deny file: 1,306,187
```

Try pulling https://hosts.ubuntu101.co.za/domains.list into your pi-hole and let me know if you find anymore false positives.
