### ISSUE TITLE
possible new lists 

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#45]
https://wally3k.github.io/

https://raw.githubusercontent.com/deathbybandaid/wally3k-adlists.list/master/adlists.list

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx have you had a look through them already to see if you spot any false positives?
don't want to be adding even more trouble into the list. Git and Travis are having issues so builds, commits and everything has slowed down. The latest build of Hosts .... yet to start .... should have all current issues fixed.

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx have you had a look through them already to see if you spot any false positives?
don't want to be adding even more trouble into the list. Git and Travis are having issues so builds, commits and everything has slowed down. The latest build of Hosts .... yet to start .... should have all current issues fixed.

**Comment by xxcriticxx** [comment]
```
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 1866989 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 1534820 unique domains trapped in the event horizon.
```

**Comment by mitchellkrogza** [comment]
Let me know how it goes.

**Comment by xxcriticxx** [comment]
as long pron works and ubuntu upgrades i should be good

**Comment by mitchellkrogza** [comment]
@xxcriticxx try pull latest raw list, found bit.ly in there which is from one of my repo's which would not deploy due to a Travis bug - https://github.com/travis-ci/travis-ci/issues/8185 which is now fixed. Let me know how it goes.

**Comment by mitchellkrogza** [comment]
@xxcriticxx pull latest raw file into pi-hole ..... it's looking nice and clean now.

https://hosts.ubuntu101.co.za/domains.list

**Comment by xxcriticxx** [comment]
sure when i get home

**Comment by mitchellkrogza** [comment]
:+1:

**Comment by funilrys** [comment]
Hello there, 

@xxcriticxx As https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/444cebc97602544f01b7daecf3390cc21cc0af4c introduce the new input source, It's may be easier to add those lists :smile: 

Once again, thanks to you @xxcriticxx for your effort :+1:
