### ISSUE TITLE
false positives: German free-mail providers

### ISSUE THREAD

**Issue by GitUser4711** [mitchellkrogza/Ultimate.Hosts.Blacklist#458]
domains like web.de and gmx.de (same for .at and more) are well-know, harmless email providers (though financed through advertisements, of course).

**Comment by funilrys** [comment]
I do not use any of them, can you give me a list?

**Comment by GitUser4711** [comment]
0.0.0.0 gmx.at
0.0.0.0 gmx.ch
0.0.0.0 gmx.com
0.0.0.0 gmx.de
0.0.0.0 gmx.es
0.0.0.0 gmx.net

0.0.0.0 freenet.de

0.0.0.0 web.de

0.0.0.0 protonmail.ch
0.0.0.0 protonmail.com

0.0.0.0 t-online.de
0.0.0.0 t-online.at

0.0.0.0 1und1.de

there are most likely more, but the number of entries in the file makes screening it a little difficult ;-)  The fact that almost every free-mail provider known around here is listed makes me wonder whether there might be a systematic issue with one of the source lists contributing to your list...

**Comment by funilrys** [comment]
We decided by design to concentrate our effort into whitelisting and input source addition.  

So yes we know that we block almost all service in the world but as long as nobody report or it does not disturb our daily navigation, we leave them.

**Comment by funilrys** [comment]
Note: `protonmail.ch` redirects to `protonmail.com`.
