### ISSUE TITLE
imasdk.googleapis.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#462]
Match found in https://hosts.ubuntu101.co.za/hosts:
imasdk.googleapis.com

breaks ps vue tv (https://en.wikipedia.org/wiki/PlayStation_Vue) per this article 

https://www.reddit.com/r/pihole/comments/9snv22/psvue_woes/

**Comment by jawz101** [comment]
Well, I just wanted to give some context but leave it whitelisted if it's blocking something.

**Comment by dnmTX** [comment]
@funilrys you can whitelist this one. It breaks several web players(nbc.com affected),also @anudeepND had 
some bad experience too so he can confirm as well. Onliest way to stop ads coming from it is with adblocker and on case to case basis.

**Comment by funilrys** [comment]
@dnmTX Good to whitelist!

**Comment by dnmTX** [comment]
@funilrys  looks like it's already has been whitelisted:
https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/577d79ab7f4d9efc192431f9328e73eacb3fa69a/domains.list#L341
I guess you can close this one.
