### ISSUE TITLE
static.xx.fbcdn.net

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#476]
breaks fb

Match found in https://hosts.ubuntu101.co.za/hosts:
   static.xx.fbcdn.net

![golden boy boxing home facebook](https://user-images.githubusercontent.com/15007183/49324896-ef1b8580-f505-11e8-9bde-eb689658a443.png)

**Comment by funilrys** [comment]
Hi @smed79, can you confirm me that it's good to go the whitelist list? 

Have a nice day/night.

Cheers,
Nissar

**Comment by dnmTX** [comment]
It's a generic domain.Most of the time delivers images,gifs,css but also java scripts and most of them are flagged on VirusTotal so i'd be cautious with this one
