### ISSUE TITLE
   pulsar.ebay.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#480]
back on the list again please see #119 

Match found in https://hosts.ubuntu101.co.za/hosts:
   pulsar.ebay.com

**Comment by dnmTX** [comment]
@xxcriticxx  i just reported it to the [right place](https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/3).I'm guessing it will be whitelisted shortly.
