### ISSUE TITLE
wikimedia.org

### ISSUE THREAD

**Issue by RezwanArefin01** [mitchellkrogza/Ultimate.Hosts.Blacklist#482]
Breaks Wikipedia and many other things. 

Match found in https://hosts.ubuntu101.co.za/hosts: 
0.0.0.0 wikimedia.org

![screenshot_20181217_074804](https://user-images.githubusercontent.com/22095441/50062219-1c3b8980-01d0-11e9-82b2-9f7a59c63285.png)

![screenshot_20181217_074951](https://user-images.githubusercontent.com/22095441/50062246-5573f980-01d0-11e9-9dac-e561609e0738.png)

(I wonder who put wikimedia there -_-)

**Comment by xxcriticxx** [comment]
(I wonder who put wikimedia there -_-) for sure @mitchellkrogza

**Comment by funilrys** [comment]
@xxcriticxx @RezwanArefin01 it comes from https://github.com/Ultimate-Hosts-Blacklist/www.shallalist.de
