### ISSUE TITLE
piratebay.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#487]
Match found in https://hosts.ubuntu101.co.za/hosts:
   
   piratebay.com

**Comment by dnmTX** [comment]
👎

**Comment by funilrys** [comment]
@dnmTX Still a top level domain... People who visit it have their own reason. I'm in favor of whitelisting this and warning user in the README about this ...

**Comment by dnmTX** [comment]
@funilrys  it's been whitelisted already so you can close this one as well:
https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/577d79ab7f4d9efc192431f9328e73eacb3fa69a/domains.list#L668

**Comment by funilrys** [comment]
Not whitelisted. It states:
```
This site is not affiliated with thepiratebay.org
```
