### ISSUE TITLE
1.1.1.1

### ISSUE THREAD

**Issue by thomas-maurice** [mitchellkrogza/Ultimate.Hosts.Blacklist#489]
This is a false positive, it breaks DNS over TLS using Cloudflare's one.one.one.one service

https://www.cloudflare.com/learning/dns/what-is-1.1.1.1/

**Comment by xxcriticxx** [comment]
```
[i] No results found for 1.1.1.1 within the block lists
[i] No results found for one.one.one.one within the block lists
```

**Comment by funilrys** [comment]
@xxcriticxx It is present into https://github.com/Ultimate-Hosts-Blacklist/BadIPs.com_KEY

**Comment by smed79** [comment]
2nd cloudflare DNS ==> **1.0.0.1**
