### ISSUE TITLE
Updates Delay (List culling and removal of dead domains)

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Ultimate.Hosts.Blacklist#49]
A big build is in progress to get a reliable output of all dead domains on this hosts list. Updates to this repo will only resume in about 7 days time.

**Comment by mitchellkrogza** [comment]
Something just interesting, can you believe that **burger-imperia.com** and **pizza-tycoon.com** are still the top ranking most active bad sites out there. Every day in all my logs across 28 sites.

**Comment by xxcriticxx** [comment]
should i visit them?

**Comment by mitchellkrogza** [comment]
Burger Imperia (but of course all the nasty stuff /click redirecting and hijacking is hidden when you visit them)

![screen shot 2017-08-29 at 5 38 36 pm](https://user-images.githubusercontent.com/9961541/29829960-16bda7d2-8ce1-11e7-9a5d-237a467cca00.png)

**Comment by mitchellkrogza** [comment]
and pizza tycoon

![screen shot 2017-08-29 at 5 39 49 pm](https://user-images.githubusercontent.com/9961541/29830010-3f963638-8ce1-11e7-8b7c-6d6ef49ab6d5.png)

**Comment by xxcriticxx** [comment]
looks like same author

**Comment by mitchellkrogza** [comment]
Absolutely and been a pain in people's back sides for years yet nobody seems to be able to take them down.

**Comment by mitchellkrogza** [comment]
So we uncovered an undocumented Travis feature. If a repo builds continually, even though all builds pare passing, for more than 48 hours. Travis CI stops building after 48 hours. 

We did however accumulate a lot of data which can be now used to start cleaning this list of dead domains beginning with all those that returned 404. The remainder of the testing I will probably do from one of my Ubuntu Servers and no tie up Travis like this. 

So possibly later today we will have our first list of dead domains to start stripping out of the final RAW files produced.

**Comment by mitchellkrogza** [comment]
Okay, so after further investigation we did not reach any sort of timeout. One of the input sources - https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/.input_sources/_Airelles_Anti_Sex_Hosts/domains.txt had an entry `cz` as a domain name which caused the testing script to exit and go into final commit mode. 

That's the whole idea of this repo is to clean up junk information like that from all these input sources / black lists out there.

**Comment by mitchellkrogza** [comment]
@xxcriticxx new raw links pushed out today. So far lists are now stripped of 19473 dead domains. So now we resume the funceble testing again.

**Comment by mitchellkrogza** [comment]
Remember each time I do a commit it pulls in fresh data so list sizes change all the time

**Comment by mitchellkrogza** [comment]
Ultimately we want this smaller lighter and more accurate no?

**Comment by xxcriticxx** [comment]
@mitchellkrogza correct

**Comment by mitchellkrogza** [comment]
:+1:

**Comment by xxcriticxx** [comment]
and no .cz domains

**Comment by mitchellkrogza** [comment]
LOL .cz yes just not cz all by itself, that issue has been resolved from all future lists where I check the combined list now for any line not containing a .  and delete it before creating the hosts files.
