### ISSUE TITLE
lwn.net should not be blocked.

### ISSUE THREAD

**Issue by John3** [mitchellkrogza/Ultimate.Hosts.Blacklist#490]

**Comment by xxcriticxx** [comment]
https://en.wikipedia.org/wiki/LWN.net

LWN.net is a computing webzine with an emphasis on free software and software for Linux and other Unix-like operating systems. It consists of a weekly issue, separate stories which are published most days, and threaded discussion attached to every story. Most news published daily are short summaries of articles published elsewhere, and are free to all viewers. Original articles are usually published weekly on Thursdays and are available only to subscribers for one week, after which they become free as well. LWN.net is part of Eklektix, Inc.
