### ISSUE TITLE
Question: Do I have a way of finding out why the IP is in the list ?

### ISSUE THREAD

**Issue by thomas-maurice** [mitchellkrogza/Ultimate.Hosts.Blacklist#492]
Hello !

I'd like to be able to "classify" IPs in the list, in other terms being able to use only a subset of the lists, for instance let's say I'm interested only in blocking the IP/domains that tie directly to malware and let go the ads through

Do I have a way of doing that ?

**Comment by dnmTX** [comment]
@thomas-maurice you can visit https://github.com/Ultimate-Hosts-Blacklist where all the lists are filtered and get the list's info as well to see which is which but unless you do some custom list on your end where you can skip what you don't need i don't think that there is a simple option to exclude some IP's from the big list provided.

**Comment by funilrys** [comment]
@dnmTX one day people will be eable to create their own list from a Web app 😉

**Comment by funilrys** [comment]
https://hosts.ubuntu101.co.za/app/contents/ Will be documented, improved and probably moved elsewhere soon but if you want to help us with feedback. Please test it! 😊

Cheers,
Nissar

P.S: Please avoid % as much as possible. We still have to optimize but for a beginning. it's still great.
