### ISSUE TITLE
m.facebook.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#493]
Match found in https://hosts.ubuntu101.co.za/hosts:
  
   m.facebook.com

**Comment by dnmTX** [comment]
Even though for some reason has not very good VirusTotal score/feedback it looks like the domain is used to login to Facebook from numerous websites like Nokia,Google,Uber and so on.
Unless somebody have different opinion on the subject i think it's safe to be whitelisted.
