### ISSUE TITLE
nba.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#498]
Match found in https://hosts.ubuntu101.co.za/hosts:

   nba.com
   wnba.com

**Comment by funilrys** [comment]
Should I whitelist @mitchellkrogza ? :wink: I hate such things :upside_down_face: 

```
> GET / HTTP/1.1
> Host: nba.com
> Host: www.nba.com
> GET / HTTP/2
> Host: www.nba.com
> GET /de/sport/ussport/nba/index.html?gr=www HTTP/1.1
> Host: www.spox.com
``` 

`wnba.com` is good to whitelist.

**Comment by dnmTX** [comment]
@funilrys  `nba.com` is the official NATIONAL BASKETBALL ASSOCIATION's website. Go visit see for yourself(it's safe)

**Comment by funilrys** [comment]
Yeah, I did but I'm questioning the redirection which is really not cool... even if I'm in Germany ...

Whitelisting even if I do not like the practice.

**Comment by dnmTX** [comment]
Well,nothing we can do about their questionable decisions on who is hosting their domains.
Still...the site is legit nevertheless.
