### ISSUE TITLE
NSFW hqporner.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#5]
adults only

**Comment by funilrys** [comment]
I think this is legitime :smile_cat:

**Comment by xxcriticxx** [comment]
(.)(.)

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/fcaa791f48194829bd090e8a15d87bb4de6b0e1d

**Comment by funilrys** [comment]
I'm reopening this and I'll for sure add this to whitelist but @mitchellkrogza have to explain why is this into BaddBoysHosts ? :thinking:
