### ISSUE TITLE
xart.com missing from hosts file

### ISSUE THREAD

**Issue by furtunadincarpati** [mitchellkrogza/Ultimate.Hosts.Blacklist#501]

**Comment by furtunadincarpati** [comment]
Oh, I just realized that there might be no malware at play there. It's just porn, and anti-porn is not the purpose of the file, right? Only malware?

**Comment by funilrys** [comment]
Hi @furtunadincarpati we are open! If you want we can setup a repository in our infrastructure just for your list. That way, it can be used elsewhere and at the same time be merged in here automatically every day.
