### ISSUE TITLE
.txt file hosting for AdvancedTomato Adblock

### ISSUE THREAD

**Issue by Kallaide** [mitchellkrogza/Ultimate.Hosts.Blacklist#502]
I know the main single file is too large for .txt hosting on Github, but couldn't you just have your system create two files instead? UHB1 and UHB2 which simply splits the list in two and then updates the hosted .txt file for those who use Router software that allows for URL lists?

**Comment by Kallaide** [comment]
AdvancedTomato is the Router replacement software and can only read files in the hosts format and I believe only as .txt

"Blacklist URL - Correct file format: 0.0.0.0 domain.com or 127.0.0.1 domain.com, one domain per line"

**Comment by funilrys** [comment]
Thanks for the feedback @Kallaide!

I'll look into this on my next system review/update!

**Comment by Kallaide** [comment]
Awesome! Glad I could help :)

**Comment by funilrys** [comment]
New layout for the multiple files on its road. It's not deployed yet but significant work has been done to implement that!

Will keep you updated @Kallaide !

**Comment by dnmTX** [comment]
> AdvancedTomato is the Router replacement software and can only read files in the hosts format and I believe only as .txt

@Kallaide i used several third-party firmwares on my routers(Padvan,DD-WRT etc.) and can assure you that this is not the case(Tomato is not that different,it's Linux based as well). Just download the file without any extension and DNSMASQ will read it and will sing.Also as i can recall the lists provided by @funilrys is a single entry one,not sure about if `0.0.0.0` or `127.0.0.1` are included but you can do that on your end after downloading it with simple command(or script): `sed -i 's/^/0.0.0.0 /g' hostfile'.
On the other hand,with such a huge file(1,000,000+ entries),the developer of DNSMASQ noted that it's been tested with that many entries and it works fine **BUT** it requires at least 1GHz or faster CPU.So make sure you meet those requirements.
If you need any help with making some basic script,let me know. 👍

**Comment by dnmTX** [comment]
> New layout for the multiple files on its road. It's not deployed yet but significant work has been done to implement that!

@funilrys  there is really no need for that.All of it can be done on the router's side with some basic script(s).

**Comment by funilrys** [comment]
You can use the hosts format as we provide several files now!

Closing.
