### ISSUE TITLE
WARNING: some source is blocking LAN

### ISSUE THREAD

**Issue by unbranched** [mitchellkrogza/Ultimate.Hosts.Blacklist#504]
Someone is adding 192.168.0.0/16 to the superhosts.deny, as a result the entire LAN is blocked from access.
The culprit source should be identified asap. **EDIT:** it's Firehol

@mitchellkrogza @funilrys

**Comment by funilrys** [comment]
Hi @unbranched  and thanks for this issue,

I recently updated the script which distribute everything. It's my fault I forgot to reimplement that. It will be fixed in the coming hours (Berlin Time).

Sorry for the disruption.

Cheers,
Nissar

**Comment by nav33n-kumar** [comment]
Hello....i copy pasted the entire host.windows text to the "hosts" ...now I'm not able to connect to internet ...lan as well as via Ethernet... And I'm not able to change hosts ..it says it's being accessed by another program... Even when done as administrator... please help
