### ISSUE TITLE
A number of hostnames needs to be removed

### ISSUE THREAD

**Issue by damianrath** [mitchellkrogza/Ultimate.Hosts.Blacklist#505]
The last update really overreached for some heavily legitimate sites for whatever reason I have no idea as they shouldn't be reported/put on any list IMHO. Sure, they have annoying subdomains that should be blocked, but the main domain shouldn't.

So, I went through my whitelist for legitimate blocked sites and listing them below for removal, please. The domains below should have their  www. CNAME unblocked as well.

Note that I updated the list and then queried it for the false positives below before noting them down here to make sure they weren't removed already.  Culprit: https://hosts.ubuntu101.co.za/domains.list

cdn.discordapp.com
dn.se
engadget.com
expressen.se
feedproxy.google.com
feeds2.feedburner.com
forum.paradoxplaza.com
forums.linuxmint.com
guru3d.com
howtoforge.com
idg.se
is.gd
kotaku.com
majorgeeks.com
namecheap.com
neowin.net
news.google.com
nordvpn.com
osnews.com
packages.linuxmint.com
prisjakt.nu
slashdot.org
store.steampowered.com
sweclockers.com
techrepublic.com
theregister.co.uk
trailers.apple.com
videocopilot.net
xkcd.com

It must be a monstrous task to maintain the lists so thank you for doing it. Highly appreciated.

**Comment by dnmTX** [comment]
@lightswitch05 sorry for the bother. I got tasked to review the domains here so they can be whitelisted.
I just need your output on few of them if you don't mind just to make sure that nothing goes through the cracks:
`feedproxy.google.com`
`feeds2.feedburner.com`
`cdn.discordapp.com`
Whenever you can.Thank you 👍

**Comment by dnmTX** [comment]
@damianrath just FYI. The domains:
`feedproxy.google.com`
`feeds2.feedburner.com`
`cdn.discordapp.com`
were not included as they were showing very bad VirusTotal score/feedback,so unless you convince me otherwise or give me some links to review/test it will stay this way.

**Comment by lightswitch05** [comment]
I'll chime in that `cdn.discordapp.com` is used by https://discordapp.com and also their iOS and Android app. Its a popular chat tool, in fact I use it myself. If I used this list, I would certainly have to whitelist that one. I have no knowledge or opinion on the other two feed hosts.

![image](https://user-images.githubusercontent.com/598803/54753130-ac65e200-4bb6-11e9-8cd2-9e8ab58fdb08.png)

**Comment by mitchellkrogza** [comment]
I have to add my +1 on that @lightswitch05 I too use discord. @dnmTX @funilrys feedproxy.google.com and feeds2.feedburner.com should be whitelisted imho

**Comment by dnmTX** [comment]
>  @dnmTX @funilrys feedproxy.google.com and feeds2.feedburner.com should be whitelisted imho

@mitchellkrogza can you give more info on those please.
@funilrys  you got the last word on this one,i trust @lightswitch05's opinion,but i have no info on the other two domains.
@lightswitch05 thanks for pitching in,appreciate 👍

**Comment by damianrath** [comment]
feedproxy.google.com & feeds2.feedburner.com are just intermediaries which some sites use to publish their RSS feeds. The services themselves are benign and should definitely not be blacklisted.

cdn.discordapp.com should be quite clear to why it shouldn't be blacklisted in the first place.

Thank you for taking care of business.

**Comment by dnmTX** [comment]
@damianrath done ☝️

**Comment by funilrys** [comment]
Great I took the time to check them all, nothing to say, good catches @damianrath. 

Added you into the contributors of https://github.com/Ultimate-Hosts-Blacklist!

Will be into the whitelist list asap.

Cheers,
Nissar

**Comment by funilrys** [comment]
Also, thanks @mitchellkrogza (Welcome (temporary ?:wink:) back) @lightswitch05  and @dnmTX.
