### ISSUE TITLE
Template breaking bug

### ISSUE THREAD

**Issue by unbranched** [mitchellkrogza/Ultimate.Hosts.Blacklist#506]
Today's update inclues the rows
##### START Super hosts.deny Block List # DO NOT EDIT #####
%%content%%
##### END Super hosts.deny Block List # DO NOT EDIT #####

at the beginning of the list, breaking the entire hosts.deny file, blocking further ssh access.

Second breaking-bug in a few weeks, looks like this one is not ready for production servers...

**Comment by mitchellkrogza** [comment]
@unbranched apologies we are building a new deployment system due to size issues. I have manually fixed commented out that line of superhosts.deny for now until @funilrys can fix the deployment script.

**Comment by funilrys** [comment]
@unbranched New version distributed without the issue. 

Thanks again and my apologies - again - for the noise.
