### ISSUE TITLE
Distribution of raw files .gz format

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Ultimate.Hosts.Blacklist#507]
Just been thinking that perhaps the distribution of the raw files to all users should be in .gz format or .tar.gz 

This makes downloading faster for users and reduces bandwidth. Right now bandwidth is not an issue just thinking ahead.

Welcome any comments and suggestions

**Comment by spirillen** [comment]
Thought:

If you are converting all raw files into tar.gz you'll add a extra workload to the recipient to untar the files, and for those using the files with pi-hole will see an issue (as far as i know about it)

But: If you are adding tar.gz as an option, i think it is a very good idea for those who obtain your list over adsl, or other poor internet connection :smiley:

**Comment by funilrys** [comment]
For the record @spirillen, we did distribute the tar.gz before... We just dropped them in order to have a reasonable repository size.

What is asked here is: Is it still useful to someone? If so we can implement the gz distribution but off repository.

Cheers, 
Nissar

**Comment by mitchellkrogza** [comment]
Good point @spirillen I did think some systems like pi-hole may have issues with this but think as @funilrys mentioned we add the .gz option and still provide the full uncompressed raw files so users have options. I know some who run a Cron to update might find the .gz a nice fast option.
