### ISSUE TITLE
Blocking all LAN

### ISSUE THREAD

**Issue by unbranched** [mitchellkrogza/Ultimate.Hosts.Blacklist#508]
It's included again

ALL: 192.168.0.0/16

**Comment by mitchellkrogza** [comment]
@funilrys which input source is this coming in from? We need to create a permanent whitelist for all private networking ranges to avoid this creeping back in every now and again

**Comment by mitchellkrogza** [comment]
```
10.0.0.0 to 10.255.255.255.
172.16.0.0 to 172.31.255.255.
192.168.0.0 to 192.168.255.255
```

**Comment by funilrys** [comment]
Service Note: Had to restart the build because the wrong version of the whitelisting tool was installed. It is now the correct one. New data will be available in the  next 10-15 minutes.

**Comment by funilrys** [comment]
@mitchellkrogza firehol1

**Comment by unbranched** [comment]
I will no longer report this

**Comment by funilrys** [comment]
Thanks @unbranched, no need to. 

Tests are written and will be improved with the time as you can see at https://github.com/Ultimate-Hosts-Blacklist/whitelist/commit/57f308ea0ac6227767901fefa8682a42eec81fdf#diff-91096435e85fc2eb752d068ef2758f5d.

It will now be checked before a release of a new version of the whitelisting tool.

Cheers,
Nissar

**Comment by funilrys** [comment]
Closing. Not present anymore at https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/superhosts.deny/superhosts7.deny:

```
ALL: 192.166.219.211
ALL: 192.166.219.43
ALL: 192.166.252.0/24
ALL: 192.166.81.0/24
ALL: 192.166.82.0/23
ALL: 192.167.119.200
ALL: 192.167.122.8
ALL: 192.167.155.70
ALL: 192.167.9.104
ALL: 192.169.136.33
ALL: 192.169.136.51
ALL: 192.169.138.33
ALL: 192.169.138.87
ALL: 192.169.140.100
ALL: 192.169.141.72
ALL: 192.169.143.36
ALL: 192.169.144.23
ALL: 192.169.146.53
ALL: 192.169.152.2
ALL: 192.169.153.42
ALL: 192.169.155.103
ALL: 192.169.155.230
ALL: 192.169.157.188
ALL: 192.169.171.149
ALL: 192.169.175.208
```

**Comment by funilrys** [comment]
Just a side note @mitchellkrogza,

Since https://github.com/Ultimate-Hosts-Blacklist/whitelist/commit/9c251b78f1658c96bfa389ffcd2bb62dcde26681, all reserved IPv4 are now whitelisted by the whitelisting tool.

Of course, tests shipped along with it to avoid future issues.

Cheers,
Nissar
