### ISSUE TITLE
0.0.0.0?

### ISSUE THREAD

**Issue by objectifnul** [mitchellkrogza/Ultimate.Hosts.Blacklist#509]
Maybe the first entry should be commented by default? If not, local servers (apache, mpd) would not be reachable from remote machines. So I edited hosts.deny like this:

```
# ##### START hosts.deny Block List # DO NOT EDIT #####
# ALL: 0.0.0.0/8
```

**Comment by funilrys** [comment]
Hi @objectifnul, thanks for pointing out. I'm currently handling this in our whitelisting tool. Will keep you updated.

**Comment by funilrys** [comment]
Hi @objectifnul, this is now implemented in our whitelisting tool. The next dataset generation in about 19 hours will clear this out.

Closing.
