### ISSUE TITLE
chomikuj.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#51]
chomikuj.pl,[2][3][4][5][6] or Chomik (Polish for hamster), is a Polish-language file hosting service founded in 2006.[6] As of February 2013 it was the 15th most popular website in Poland.[1]

Any type of file can be published on the web site. Unregistered users can instantly retrieve files sizes of 1 MB. After registration, a user is not subject to any limit when downloading a single file, but is limited to 50 MB transfer a week. Transfer limit can be increased by paying for additional bandwidth.[citation needed]

In 2015 it was successfully sued for copyright infringement.[7]

**Comment by mitchellkrogza** [comment]
Will add to false-positives central control. Will be removed in next build.

**Comment by mitchellkrogza** [comment]
Was fixed in last commit, domain has been added to central false-positives control list.
