### ISSUE TITLE
Download failed because of outdated certificate (PiHole, wget and Browser)

### ISSUE THREAD

**Issue by SwissSkynet** [mitchellkrogza/Ultimate.Hosts.Blacklist#511]
**wget:**
```
--2019-04-24 22:50:28--  https://hosts.ubuntu101.co.za/domains.list
Resolving hosts.ubuntu101.co.za (hosts.ubuntu101.co.za)... 149.56.195.48, 2607:5300:60:775e::5
Connecting to hosts.ubuntu101.co.za (hosts.ubuntu101.co.za)|149.56.195.48|:443... connected.
ERROR: The certificate of ‘hosts.ubuntu101.co.za’ is not trusted.
ERROR: The certificate of ‘hosts.ubuntu101.co.za’ has expired.
The certificate has expired
```
**Browser:**
![avpui_cxGl9qKCai](https://user-images.githubusercontent.com/30077849/56693410-a9de3700-66e4-11e9-9400-ca2a29ff633b.png)

**PiHole:**
Same as wget. Failed because oudated certificate.

**Comment by mitchellkrogza** [comment]
Thank you @SwissSkynet for reporting. Caused by an upgrade to the server which broke certbot. Issue resolved and new certificate issued. Please confirm.

**Comment by SwissSkynet** [comment]
Confirmed. Thank you.
