### ISSUE TITLE
New Porn Site Additions

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Ultimate.Hosts.Blacklist#512]
Received this request via email, not sure which list we should add to.

```
Please add these Porn Sites to : https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/hosts/hosts0

desipapa.xxx
dirtypornphotos.com
indiansexphotos.com
indiankinkygirls.com
unseenmms.com
indiangirlsclub.com
hotnakedgirls.net
ooodesi.com
provocationstudio.ru
xbombo.com
the-urbn.com
indiansexvideos.porn


Thanks,
Sunil
```

**Comment by funilrys** [comment]
We should document that case. Will be back in few hours (I'm on mobile). Also @mitchellkrogza the new deployement tool is ready. I'll deploy it over all input sources repos in few hours or tomorrow. 

P.S: It's will not be a waste of ressource to have an input source juste for "him/her" as the new deployement took is actually pretty fast 😸 But yeah let's discuss about it 😉

**Comment by dnmTX** [comment]
> not sure which list we should add to

Anywhere **BUT** in [Badd-Boyz-Hosts](https://github.com/mitchellkrogza/Badd-Boyz-Hosts) please.

**Comment by mitchellkrogza** [comment]
:grin: exactly why I asked first @dnmTX hate to get myself into trouble :grimacing: maybe I'll just setup a separate porn list that people can choose to use in their hosts or not, I have many many porn sites which are referrer spammers and are on my nginx and apache projects.

**Comment by funilrys** [comment]
Just NOT now :wink:

**Comment by mitchellkrogza** [comment]
I just put them into a completely separate repo > https://github.com/mitchellkrogza/Badd-Boyz-Porn

**Comment by dnmTX** [comment]
Thanks @mitchellkrogza . Separate repo is the way to go on this one.
