### ISSUE TITLE
add xorcan hosts

### ISSUE THREAD

**Issue by xorcan** [mitchellkrogza/Ultimate.Hosts.Blacklist#515]
take a look.

https://github.com/xorcan/hosts
https://github.com/xorcan/hosts/blob/master/xhosts.txt
https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt

**Comment by funilrys** [comment]
Closing as addition request should be done into our backend environment. 

Created an issue: https://github.com/Ultimate-Hosts-Blacklist/dev-center/issues/34 .
