### ISSUE TITLE
Support from hostsVN - advertising block of Vietnam

### ISSUE THREAD

**Issue by bigdargon** [mitchellkrogza/Ultimate.Hosts.Blacklist#516]
Hello!

I am from Vietnam, I have a project `hostsVN` for the purpose of blocking ads and tracking from advertisers from Vietnam. Wishing to support ad blocking projects that support blocking domains in Vietnam, so I created this issue hoping you will merge with hostsVN. The project has been maintained for more than 1 year and continuously updates new domain names.

Github: https://github.com/bigdargon/hostsVN/

Some sources use hostsVN:
- https://abpvn.com/android/
- https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/2437fd7f0b9586ef53a417dd63a59deac43452b0/Filters/filter.template#L92
- in `nextdns` lists

I have a hosts file that supports all advertisers and followers that Vietnamese people regularly access. Link https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts

And the hosts file I categorized only includes domain name blocking ads and tracking in Vietnam. I hope you just need to merge this file. Link https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-VN

Thanks you!

**Comment by bigdargon** [comment]
Update: hostsVN has been updated to Steven Black's hosts https://github.com/StevenBlack/hosts/releases/tag/2.5.0

**Comment by funilrys** [comment]
Hello and thanks for your interest!

Unfortunately, this repository is just our "frontend" (Basically just a distributor). Therefore let's continue the discussion about this in our backend at https://github.com/Ultimate-Hosts-Blacklist/dev-center/issues/36. 

Cheers,
Nissar
