### ISSUE TITLE
gp.se and www.gp.se false positive

### ISSUE THREAD

**Issue by denizdogan** [mitchellkrogza/Ultimate.Hosts.Blacklist#518]
This is the biggest newspaper in Gothenburg, Sweden and should not be blocked.

**Comment by funilrys** [comment]
Hello and thanks for your interest!

Unfortunately, this repository is just our "frontend" (Basically just a distributor). Therefore let's continue the discussion about this in our backend at https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/81. 

Cheers,
Nissar
