### ISSUE TITLE
Taking infinite time to load

### ISSUE THREAD

**Issue by rushic24** [mitchellkrogza/Ultimate.Hosts.Blacklist#523]
I tried both with and without batch script, firefox doesn't load a single google search.
stuck at infinite loading.

**Comment by mitchellkrogza** [comment]
Your Operating System ?

**Comment by rushic24** [comment]
> 
> 
> Your Operating System ?

Windows10

**Comment by mitchellkrogza** [comment]
The hosts file is just too big for Windows, I had the same problems. 
Wait for our DNS based service which does a much better job and puts no load on your system
