### ISSUE TITLE
ceneo.pl otomoto.pl - businesses with a good reputation on the blacklist

### ISSUE THREAD

**Issue by wlodek76** [mitchellkrogza/Ultimate.Hosts.Blacklist#528]
Hello Mitchell,

Thank you for a great database of different malicious sites.
It is very handy for network administrators.

However there are some big shopping (items selling) sites on the blacklist, probably added by a mistake. These sites are very popular in Poland.

**http://ceneo.pl
http://otomoto.pl
http://www.ceneo.pl
http://www.otomoto.pl**

Could you remove these sites from the blacklist, please?

**Comment by dnmTX** [comment]
**PING** @funilrys 
This one is from another **adblock list**,no point to whitelist it,see if you can figure it out how to filter better those lists.

**Comment by mitchellkrogza** [comment]
Indeed these originate from adblock.mahakala.is

![2019-10-08_09-15](https://user-images.githubusercontent.com/9961541/66374743-f9bb6c80-e9ab-11e9-8e56-f0d144a6018c.png)

**Comment by spirillen** [comment]
Hi everyone

I personally stopped using `mahakala.is` as there are way to many false-positives, last time i check ~6-7 month ago I did get more than 1000 fp's

It's just a note...

**Comment by mitchellkrogza** [comment]
We should consider dropping this then. There's a number of lists I started with a very long time ago and many seem to have fallen by the way side and are also no longer maintained. Also have no way to check when mahakala was last updated as their domain simply serves you a host file which also contains no date of last update or anything.

**Comment by spirillen** [comment]
https://github.com/pi-hole/pi-hole/issues/35 just another thread describing the issue with that list

**Comment by funilrys** [comment]
I'm okay with deletion. Give me your voices @dnmTX @mitchellkrogza and I'll try to schedules deletion (if it's the one who wins :wink:) asap.

Cheers,
Nissar

**Comment by dnmTX** [comment]
Considering what @mitchellkrogza posted above,i have nothing else to add. Very much **OK** with deletion 👍 

P.S. @funilrys  still...the issue with how the adblock lists are filtered which causing legit domains to be blocked is present. Just a reminder.

**Comment by dnmTX** [comment]
@funilrys  apologies for assuming the wrong thing. I just downloaded the original `adblock.mahakala.is` and it turns out that it's a hosts file and not adblock list.So somebody decided to convert a adblock list into a hosts file without making any effort to sort it out and remove the legit domains.And of course there are whole lot false positives there.One more reason to remove it,less headache for everyone here.

**Comment by mitchellkrogza** [comment]
I second removal as I saw the same yesterday when I visited their link

**Comment by funilrys** [comment]
Repository deleted. Will be removed from the list tomorrow.

@dnmTX, @mitchellkrogza, feel free to close.

**Comment by dnmTX** [comment]
> @dnmTX, @mitchellkrogza, feel free to close.

Don't have the authority here for such a action so passing the ball to @mitchellkrogza 😉
