### ISSUE TITLE
bgr.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#53]
```
::: /etc/pihole/list.41.hosts.ubuntu101.co.za.domains (1 results)
0.0.0.0 bgr.com
```

Boy Genius Report (also referred to as BGR) is a technology-influenced website that covers topics ranging from consumer gadgets, to entertainment, gaming, and science. Founded in October 2006 by anonymous web personality Boy Genius (also referred to as BG/BGR), the site was previously based on offering the public an early look at upcoming mobile phones and devices before anyone else. On April 27, 2010, BGR was acquired by Penske Media Corporation.[2]

**Comment by mitchellkrogza** [comment]
Has been added to central false-positives control list. Will be fixed in next build later today, just waiting for current list re-testing of dead domains to complete.

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/5d5ff44b23fcb693968f868241a4fc4a52d92733 

2 Input sources re-added so list has grown again. Now time for re-testing for another round of dead-domains.

**Comment by mitchellkrogza** [comment]
@xxcriticxx fresh raw links available for you.
