### ISSUE TITLE
Where is addons.mozilla.org listed?

### ISSUE THREAD

**Issue by Somebodyisnobody** [mitchellkrogza/Ultimate.Hosts.Blacklist#531]
Hello together. How can I see where addons.mozilla.org is listed in the sources?
@funilrys you mentioned a tool you was working on. Is it in progress?

**Comment by dnmTX** [comment]
@Somebodyisnobody  it's listed in [Phishing.Database](https://github.com/mitchellkrogza/Phishing.Database/blob/master/phishing-domains-ACTIVE.txt) 😉 
For any feature inquiries refer to: https://hosts.ubuntu101.co.za/app/contents/ 👍
