### ISSUE TITLE
Allow di.phncdn.com & ci.phncdn.com

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#532]
These are breaking Pornhub from loading properly :)

**Comment by dnmTX** [comment]
Just tested it,with both domains blocked by default and didn't encounter a single issue with loading or watching any video. @p1r473  most likely the issues you experiencing are residing somewhere else.
Mitch @mitchellkrogza  you can close this if you want,no need of further debate,`pornhub.com` is working as expected.

![Capture](https://user-images.githubusercontent.com/34774426/70199283-e8a28980-16d6-11ea-8bbe-39ab941ac4df.PNG)

**Comment by p1r473** [comment]
Still an issue. I am not able to re-open this issue, so I have opened #539

**Comment by p1r473** [comment]
All good now, thanks!
