### ISSUE TITLE
Host list cannot be used for pfBlockerNG

### ISSUE THREAD

**Issue by m0urs** [mitchellkrogza/Ultimate.Hosts.Blacklist#536]
The hosts file cannot be used in pfBockerNG (a blocking script like Pi Hole for fSense routers). The reason is the use of some special characters in the header like
```

line 9:
#     / / \ \ | __| | '_ ` _ \ / _` | __/ _ \                             #

```
Some other lines in that header as well.

Error message:

[DNSBL Source Definitions, Line 9: Header field cannot contain spaces, special or international characters.](url)

Maybe we can just delete that (graphic like) header?

Thanks,
Michael

**Comment by funilrys** [comment]
Header updated @m0urs, can you confirm that it's gone ?

**Comment by m0urs** [comment]
Yes, that fixed it. Thank you very much!
