### ISSUE TITLE
Block various domains accessed by trojan

### ISSUE THREAD

**Issue by Somebodyisnobody** [mitchellkrogza/Ultimate.Hosts.Blacklist#538]
After executing a trojan on an isolated host system I got following domains on my dns-server:
lodddd01.info
jload01.info
rifat01.info
Some other requested domains were already blocked, I assume they are here in the list.
Attached a traffic capture where you can see which files are being downloaded (e.g. stream 3 where "jload01.info/downfiles/1.exe" is called or stream 0 where a zip with
```
 ....I^..I^..I^{.{?.PK..........PP................Browsers/_FileForms.txtUT
....I^..I^..I^{.{?.PK..........PP................Browsers/_FilePasswords.txtUT
....I^..I^..I^{.{?.PK..........PP................_FilePasswords.txtUT
....I^..I^..I^{.{?.PK..........PP............	..._Info.txtUT
```
is being uploaded to rifat01.info. The zip attached is extracted from the stream)

[trojan_filtered.zip (wireshark capture file)](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/files/4210892/trojan_filtered.zip)
[index.php.zip](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/files/4216198/index.php.zip)
[trojan.zip](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/files/4216175/trojan.zip)  **(only download if you know how to handle a trojan, password "trojan")**

**Comment by spirillen** [comment]
May I suggest you to add a password to the `trojan.zip` rather than just redistribute it as is and at  the same ensuring people not execute by mistakes?
