### ISSUE TITLE
false positive https://promo-bc.com removal request

### ISSUE THREAD

**Issue by tinselx** [mitchellkrogza/Ultimate.Hosts.Blacklist#545]
Hello, please remove domain promo-bc.com from you DB, we use it inside our affiliate system bongacash.com. There are no any suspicious things.

Thanks

**Comment by dnmTX** [comment]
@tinselx  this domain is blocked by reputable curator's [lists](https://gitlab.com/quidsup/notrack-blocklists).You can open a [issue](https://gitlab.com/quidsup/notrack-blocklists/issues) there and discuss it further as i'm not convinced so far to whitelist it on our end.Looking at the comment left by the curator,this is just the thing we trying to protect the users from,ourselves as well 👇 
![notrack-malware](https://user-images.githubusercontent.com/34774426/75422284-d0bb5a00-5901-11ea-89db-5de8a6d065c6.png)
