### ISSUE TITLE
Please remove our business domain name from the Blacklist

### ISSUE THREAD

**Issue by brightedgecops** [mitchellkrogza/Ultimate.Hosts.Blacklist#549]
Brightedge Technologies is a legitimate business based in US, and we have over 1700 customers worldwide.  We found out that our domain name has been added to the Ultimate.Hosts.Blacklist.
Please remove our domain (brightedge.com) and all our hosts from this list, as this is undermining our domain reputation, and causing problems in our business operation.   
We also would like to know how our domain name had been added to the blacklist, as we would like to prevent this problem from occurring again in the future.  So please provide us with all records related to our domain and our hosts.
Thanks.

**Comment by dnmTX** [comment]
:balloon:
