### ISSUE TITLE
tosiewytnie.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#55]
::: /etc/pihole/list.41.hosts.ubuntu101.co.za.domains (1 results)
0.0.0.0 tosiewytnie.pl

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx added to false positives on https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects and will be stripped out on next build. Keep em coming 👍

**Comment by mitchellkrogza** [comment]
@xxcriticxx @funilrys if either of you can think of any domains which should be permanently whitelisted always, [please review the list here](https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/blob/master/whitelist-domains.txt) and either send a PR with more domains to be whitelisted or simply list them in Issues on that repo and I will add them.

**Comment by funilrys** [comment]
@mitchellkrogza I didn't look into the code but do you use regex match? Cause for example:

It'll save us some bytes to have

- `google.com` ==> can match `dl.google.com` and `drive.google.com`
- `apple.com` ==> can match `itunes.apple.com`
- `cnn.com` ==> can match `money.cnn.com`
- `ubuntu.com` ==> can match `archive.ubuntu.com`

I don't know what you think about it but I think it can be great assuming that only legitimate (big company or well-known website) domains are on that whitelist.

**Comment by mitchellkrogza** [comment]
I agree totally, haven't figured out a regex in my cleaning functions to handle that. Much better to have just root domains and then *.domain.com get's stripped out of hosts lists. Do you want to review those list cleaning functions for me ??? You're smarter with Regex than me 😁

**Comment by xxcriticxx** [comment]
https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx those have now all been whitelisted in https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/commit/047231eb58dc03149753fb7f8146d1de939047a2

**Comment by mitchellkrogza** [comment]
@xxcriticxx we still have about another 5 days of dead domain testing to go before fresh links get pushed out again.

**Comment by xxcriticxx** [comment]
@mitchellkrogza no problem!

**Comment by mitchellkrogza** [comment]
https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/199b042ab442a092702c3ce7bda7055e1be4f502 Fix: #55

**Comment by mitchellkrogza** [comment]
@xxcriticxx fresh raw links pushed out today. Continuation of dead domains testing continuing in a separate environment.
