### ISSUE TITLE
False Positive: apkpure.com

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#551]
Hi,
the domain blocked is apkpure.com
This is for downloading Android applications
I believe this is a false positive as there is legitimate reasons for wanting to download an APK and sideload it onto an Android device.

**Comment by dnmTX** [comment]
![Blacklist](https://user-images.githubusercontent.com/34774426/77217139-2d1f2d00-6aee-11ea-87f2-75c76e6014bf.png)

@funilrys  just in case double check(the search might be broken),otherwise close.Thanks 👍

**Comment by p1r473** [comment]
![image](https://user-images.githubusercontent.com/9235633/77218039-922e4f00-6afd-11ea-8d82-7b473f03520e.png)

**Comment by dnmTX** [comment]
Ok,the search is working again. This one goes to Mitch @mitchellkrogza ,it's listed in [Phishing.Database](https://github.com/Ultimate-Hosts-Blacklist/Phishing.Database).
