### ISSUE TITLE
www.googletagmanager.com breaks Hearthstone login from iOS

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#552]
www.googletagmanager.com breaks Hearthstone login from iOS
Not sure if you want to whitelist or leave as is
Feel free to close.
This issue is just an FYI for breaking a site.

**Comment by dnmTX** [comment]
> Not sure if you want to whitelist or leave as is

I can assure you that it will not. You need to do it on your end. Also if you don't mind,close it.

**Comment by p1r473** [comment]
@dnmTX It will not what? Break Hearthstone login on iOS?
