### ISSUE TITLE
ebates.com False Positive

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#553]
The domains:
ebates.com
www.ebates.com

It is a legitimate website that allows users to get cashback for their purchases
(I use it myself)
Feel free to close if you disagree

**Comment by dnmTX** [comment]
@funilrys the domain is listed in two lists:
[Global-Advert-Servers-Blocklist](https://hostsfile.mine.nu/) which,by the look of it,hasn't been updated for a long time,not sure if it's even maintained anymore:
![ HOSTSFILE MINE NU     HOSTS FILE PROJECT ](https://user-images.githubusercontent.com/34774426/77230205-8c1d8a00-6b60-11ea-888e-1000623ec553.png)

[Cameleon Project](http://sysctl.org/cameleon/) which is abandoned for more then two years:
![The CAMELEON Project - Philippe Bourcier](https://user-images.githubusercontent.com/34774426/77230263-0c43ef80-6b61-11ea-975d-8ecf701cdd60.png)

You can move this to us so we can discuss it further if you want. Thanks 👍
