### ISSUE TITLE
NTP servers- False Positives

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#554]
Domains:
pool.ntp.org
www.pool.ntp.org

These are servers for Network Time Protocol and are totally benign

**Comment by dnmTX** [comment]
Yep. This is definitely false-positive and it comes from a lists that suppose to block only Turkish websites: https://github.com/xorcan/hosts
@p1r473 open a issue there and if the curator doesn't want to remove it,will take care of it on our end.
@funilrys  move it to us please.Thanks 👍

**Comment by p1r473** [comment]
Removed from curator
https://github.com/xorcan/hosts/issues/5
