### ISSUE TITLE
reddit.app.link False Positive

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#555]
This is reddit's "open in app" service
Clicking a link from this domain goes from browser->Reddit app (on mobile)

**Comment by dnmTX** [comment]
@p1r473  for this one,you can report it [upstream](https://github.com/lightswitch05/hosts/issues) and go  from there.The lists comes from a trusted source and i know for a fact that the curator is very careful on which domains are being blocked there. You can also close it here as no action will be taken anyway.
