### ISSUE TITLE
s.youtube.com

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#556]
A frequently whitelisted domain, used by Youtube for storing your watched history, and serving recommendations
If you disagree with this, please feel free to close this issue.

**Comment by dnmTX** [comment]
This has been discussed many times in many blacklist's repos. It's a tracking domain and most of us using such a lists to at least try to better protect our privacy so the request here to be whitelist it is straight up denied. You can also close this one.

**Comment by p1r473** [comment]
Thanks

**Comment by p1r473** [comment]
No problem thanks
