### ISSUE TITLE
socialize.us1.gigya.com - breaks iRobot app

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#558]
Not sure how you want to handle this one, as it is social related, but blocking this breaks the iRoomba/iRobot vacuum app (can't log in)
I have whitelisted it on my end. Feel free to close this one. (This issue is just an FYI for breaking a website, if you want to add a comment or something around that line)

**Comment by dnmTX** [comment]
@p1r473  same as https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/555#issuecomment-602060838
