### ISSUE TITLE
jdownloader.org

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#56]
::: /etc/pihole/list.41.hosts.ubuntu101.co.za.domains (5 results)
0.0.0.0 jdownloader.org
0.0.0.0 update1.jdownloader.org
0.0.0.0 update2.jdownloader.org
0.0.0.0 update3.jdownloader.org
0.0.0.0 update4.jdownloader.org

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx fixed in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/4965ca8fb00a24f7cc9195d381ba9a990025e824
