### ISSUE TITLE
False Positive: aljazeera.com www.aljazeera.com

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#566]
Hi,
The following domains belong to a well known news agency.
aljazeera.com 
www.aljazeera.com

I believe this was mistakenly blocked in your hosts file.

**Comment by dnmTX** [comment]
@p1r473 are you sure? The search engine can't find it in the database but considering that sometime gets broken i would ask you to double check on your end please.

**Comment by p1r473** [comment]
![image](https://user-images.githubusercontent.com/9235633/78111515-c42b9500-73ca-11ea-8b20-7739049fd316.png)

**Comment by p1r473** [comment]
![image](https://user-images.githubusercontent.com/9235633/78111580-e1606380-73ca-11ea-9df5-7767a186ee8e.png)

**Comment by dnmTX** [comment]
@funilrys  another one from [Airelles_Anti_Sex_Hosts](https://github.com/Ultimate-Hosts-Blacklist/Airelles_Anti_Sex_Hosts).I'm also start leaning towards dropping that list due to very obvious false-positives.
Move it to us please.Thanks 👍

**Comment by funilrys** [comment]
@dnmTX will look into the deletion request ASAP(can't give a datetime) .

**Comment by p1r473** [comment]
@dnmTX I would agree, as anti-sex is very censoring, and I don't think the Ultimate Blocklist should censor!

**Comment by funilrys** [comment]
@p1r473 ==> Please follow the new link after a move. 
Locking.
