### ISSUE TITLE
disqus.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#57]
Disqus (pronounced discuss) is a worldwide blog comment hosting service for web sites and online communities that use a networked platform. The company's platform includes various features, such as social integration, social networking, user profiles, spam and moderation tools, analytics, email notifications, and mobile commenting. It was founded in 2007 by Daniel Ha and Jason Yan as a Y Combinator startup.

In 2011, Disqus ranked #1 in Quantcast's U.S. networks with 144 million monthly unique U.S. visits.[3] Disqus has been featured on many major publications, such as CNN, The Daily Telegraph, and IGN, and about 750,000 blogs and web sites.[4]

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx fixed in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/4965ca8fb00a24f7cc9195d381ba9a990025e824 Fresh Raw Links Available

**Comment by funilrys** [comment]
Another :1st_place_medal: :joy_cat:

**Comment by mitchellkrogza** [comment]
@xxcriticxx you will notice that updates and fixes will now be much quicker as the testing of dead-domains is now being run in a separate repository so it does not tie this one up for days. So keep those false positives coming and thanks again for all your contributions 👍 

@funilrys definitely disqus.com should be in the hall of fame.
