### ISSUE TITLE
False Positive: Etsy

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#571]
www.etsy.com
etsy.com

This is a online marketplace for handmade goods

**Comment by dnmTX** [comment]
@funilrys  `@Phishing.Database` Thanks 👍 

@p1r473  see:
https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/572#issuecomment-608698118

**Comment by p1r473** [comment]
Thanks 
https://github.com/mitchellkrogza/Phishing.Database/issues/51
