### ISSUE TITLE
Breaking site: x.kinja-static.com

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#572]
Hi, not sure how you want to handle this one
This one breaks Gozmodo news articles, but also lets in some ad pictures.

![image](https://user-images.githubusercontent.com/9235633/78388479-1a592d80-75af-11ea-89ed-a1751758c1de.png)
![image](https://user-images.githubusercontent.com/9235633/78388502-204f0e80-75af-11ea-9547-b77e67ed3ef6.png)

**Comment by dnmTX** [comment]
@p1r473 see: https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/135#issuecomment-608156712

This is me,handling it 😉

**Comment by p1r473** [comment]
@dnmTX okay thanks. I had reported it Upstream too already
https://github.com/yous/YousList/issues/128
