### ISSUE TITLE
1drv.ms still on domains.list but not found in the backend

### ISSUE THREAD

**Issue by Somebodyisnobody** [mitchellkrogza/Ultimate.Hosts.Blacklist#575]
I already wrote about that http://1drv.ms/ is a redirect service for microsoft office shares. It was whitelisted after (I cannot find the issue).
I cannot find the domain with https://hosts.ubuntu101.co.za/app/contents/ in the backend but it's still in the [domains.list](https://hosts.ubuntu101.co.za/domains.list)
Something is wrong there...

**Comment by dnmTX** [comment]
> Something is wrong there...

The search is buggy sometimes and it doesn't show any results for some reason.
It's working now and it found the domain in two of the lists here:
![Blacklist](https://user-images.githubusercontent.com/34774426/79332231-151aad80-7ee2-11ea-8fe1-7974b7460e2b.png)

**Comment by Somebodyisnobody** [comment]
Oh thank you very much!
