### ISSUE TITLE
[FALSE-POSITIVE] news.bitcoin.com

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#578]
This domain comes from our locally cached copy of the now defunct https://github.com/ZeroDot1/CoinBlockerLists/
We can remove it from our local copy https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
It is news related to Bitcoin

**Comment by dnmTX** [comment]
@p1r473  open a issue in his [GitLab Repo](https://gitlab.com/ZeroDot1/CoinBlockerLists/-/issues) and discuss it there with the curator and will go from there i guess.
Just in case **PING @ZeroDot1**. With some luck he might respond here.

**Comment by p1r473** [comment]
Whoops sorry.

**Comment by p1r473** [comment]
@dnmTX Whoops sorry- didn't realize his Github moved to Gitlab.
I did not know about the JSON- will check those in the future. I only looked at the part of our Git that said ```Test of https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list.txt```

https://gitlab.com/ZeroDot1/CoinBlockerLists/-/issues/59 - closed the issue, saying "Because a mining pool is running via bitcoin.com, this subdomain is also blocked. Every user can create his own white list."

Will whitelist on my own end.

**Comment by p1r473** [comment]
I tried to edit the topic of the ```Test of https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list.txt``` through a pull request but apparently topics can't be edited through PRs

**Comment by dnmTX** [comment]
> but apparently topics can't be edited through PRs

**PING @funilrys** it's probably a good time/idea the description to be changed to show the new 
GitLab URL.

@p1r473 thanks to pointing this one out,let's hope @funilrys will find some time and correct it.
Sorry it didn't work out but @ZeroDot1 know his stuff so will leave it at that 😉
