### ISSUE TITLE
tracker list 

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#58]
can you please run this list

https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx again for your contributions. This source has now been added in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/0c6a9078eb134635d2f81858c75af576404012e2 and will be updated on each build. 👍
