### ISSUE TITLE
[FALSE-POSITIVE] staticxx.facebook.com

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#582]
Hi gents,
need some help on this one.

I found staticxx.facebook.com in
https://hosts.ubuntu101.co.za/domains.list 
and
https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/domains/domains1.list 

However, when looking on our platform, the domain seems to be in the whitelisted and clean lists.
I am not too sure what to make of this.
I emailed Wally3k to tell him about the False Positive. I did not do a PR for Smed79 as I believe the domain is blocked on purpose in "smed79_blocklist_facebook"
I am not too sure how these whitelisted domains made it into the domain.list. 
Please advise, thanks!

I believe this domain is a static asset CDN for facebook, and it used to serve photos (not ads)

A CDN, or Content Delivery Network, is a network of different servers used to make sure that your web content is accessed from a server near you, to maintain speed.
Static content is content that does not change, such as uploaded images.
fbcdn.net is the CDN that Facebook owns and uses, and static means that you’re getting static data instead of dynamic data.

Apologies in advance for any errors or mistakes!

![image](https://user-images.githubusercontent.com/9235633/82245926-d4afb480-9911-11ea-8db0-0647d436769c.png)

**Comment by dnmTX** [comment]
@p1r473 no mistakes and thanks for reporting this. The @smed79's facebook list is not include in the Ultimate.Hosts... anymore and it's here just to be filtered. I see that you already reported it to the proper upstream so let's wait and see the response from @Wally3k . See if you can find the list's repo and open a issue there,might be faster this way. Keep us informed of the development.

@funilrys move it to us please.Thanks 👍

**Comment by WaLLy3K** [comment]
I can see how this URL got into my blocklist, and I appreciate you bringing this to my attention @dnmTX!

My list has been updated to remove `staticxx.facebook.com`.

**Comment by dnmTX** [comment]
Thanks for that fast response @WaLLy3K and resolution 👍 
@p1r473 you can close this one as it was resolved from upstream.

**Comment by funilrys** [comment]
Moved for history purpose. Thanks for handling this @WaLLy3K @p1r473 @dnmTX.
