### ISSUE TITLE
[FALSE-POSITIVE] change.org www.change.com

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#583]
Hi guys,
I think a false positive made it on the list. 
change.org www.change.com
This is a petition signing website- not malicious
I checked the platform, and couldn't find it

![image](https://user-images.githubusercontent.com/9235633/82615486-8829da80-9b98-11ea-97b4-13e74a84917c.png)
.

**Comment by p1r473** [comment]
Its working now. https://github.com/mitchellkrogza/Phishing.Database/issues/82

**Comment by funilrys** [comment]
@p1r473 I'm aware of the problem with the platform :disappointed: I'll look into it in the coming weeks...
