### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by Wiggum127** [mitchellkrogza/Ultimate.Hosts.Blacklist#589]
Have added the hosts file to the collections of hosts files filtering local traffic.
Found two legitimate websites no longer working because of entries in your hosts file:

s3-us-west-1.amazonaws.com
www.auslogics.com

Whitelisting those addresses allowed the websites to function again. Please drop these entries from your repo.

**Comment by dnmTX** [comment]
@funilrys  `s3-us-west-1.amazonaws.com` belongs to Phishing.Database so move it there and to us please. Thanks 👍

**Comment by dnmTX** [comment]
@Wiggum127  `www.auslogics.com` is listed in [@quidsup's malicious list](https://gitlab.com/quidsup/notrack-blocklists/-/blob/master/notrack-malware.txt) and it's one of our much trusted sources here.
You can open a [ISSUE](https://gitlab.com/quidsup/notrack-blocklists/-/issues) there and discuss it further with him and if he removes it from his list it will not be present here as well.

**Comment by dnmTX** [comment]
**For tracking purpose:**
https://gitlab.com/quidsup/notrack-blocklists/-/issues/32
