### ISSUE TITLE
About Super.Hosts (included in Blackweb)

### ISSUE THREAD

**Issue by maravento** [mitchellkrogza/Ultimate.Hosts.Blacklist#6]
Great work. We have included your list (Ultimate Super.Hosts Blacklist ) in Data sheet (sources) of our [Blackweb](https://github.com/maravento/blackweb) project based on Squid-Cache for Linux
Special Thanks

**Comment by funilrys** [comment]
Nice :+1: :smile_cat: 

@mitchellkrogza is on holiday but I think he would say : AWESOME :+1: :100: :1st_place_medal: :star: :trophy: 

I'm working on a better way to clean this repository with [funceble](https://github.com/funilrys/funceble) so maybe when he come from holiday my next release or pre-release will handle big file automation with travis :smile_cat:

**Comment by maravento** [comment]
Great. To express our congratulations

**Comment by mitchellkrogza** [comment]
That's awesome news. Yes I am indeed on holiday but this is certainly great
to hear. Still lots of fine tuning needed on this list but so glad it been
included as a source for your project.

**Comment by maravento** [comment]
**Abour The-Big-List-of-Hacked-Malware-Web-Sites**:
[](https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/blob/master/hacked-malware-websites.txt)
The content of this list, is included in superhosts.deny.zip?. Thanks

**Comment by mitchellkrogza** [comment]
Hi @maravento I am back from trip away, 👍 thanks so much for including this and my other sources in your BlackWeb Project. I have pushed out some new updates today, removed a few false positives and the list size of Ultimate Hosts has grown again with fresh data from remote sources.

**Comment by maravento** [comment]
great news.

**Comment by mitchellkrogza** [comment]
@maravento been doing some big cleaning up and de-duping. Busy with another big clean of dead and expired domains but that's going to take some time to complete but you will see the list is reduced somewhat and has not one dupe. Found an error in my scripting where some input files were in a DOS format causing dupes to be created but all fixed now.

**Comment by maravento** [comment]
thanks for the info. I will update blackweb, but there is a problem. I would need the list of excluded domains to exclude them also from blackweb

**Comment by mitchellkrogza** [comment]
@maravento Can you possibly send me the list you have so I can run it against current list and provide you with the removed stuff? Does blackweb not pull it from the repo and update it?

**Comment by maravento** [comment]
Blackweb does not eliminate. Only adds bad domains (except whitelist)
https://github.com/maravento/blackweb/tree/master/bl
cat blackweb.tar.gz* | tar xzf -

**Comment by mitchellkrogza** [comment]
@maravento it's taken several weeks of work but we now have a central repo for controlling removals of dead domains, dead blogspot domains & more coming. 

This central repo also controls whitelisting and removal of false positives.

So all projects now draw from this central information and have list cleaning functions which do the stripping and removals on every build.

The central control system can be found at : https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects and we'd love any contributions or additions from you, simply send PR's wherever applicable.

Right now on dead domains we have a 99% accuracy rate. Each list will be re-tested from time to time to check for domains or web sites that have become re-active and they will be added the re-active-domains list.

This now gives much better control across all repo's and reduces any whitelisted or false positive domains ever being re-added to a list by mistake.

**Comment by mitchellkrogza** [comment]
So @maravento you can still do regular pulls of the domains lists from:

[Ultimate Hosts](https://hosts.ubuntu101.co.za/domains.list)

[Hacked Malware Web Sites](https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list)

[Badd Boyz Hosts](https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/PULL_REQUESTS/domains.txt)

[Nginx Ultimate Bad bot Blocker](https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-referrers.list)

**And then run your removals / cleaning using**

[CENTRAL REPO - Dead Domain - All Combined](https://raw.githubusercontent.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/master/dead-domains-ALL-combined.txt)

[CENTRAL REPO - Whitelisted Domains](https://raw.githubusercontent.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/master/whitelist-domains.txt)

[CENTRAL REPO - False Positives](https://raw.githubusercontent.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/master/false-positives.txt)





https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-referrers.list

**Comment by maravento** [comment]
Great news. On Monday we will update blackweb project with the new repositories. 
An important question:
This list:
[Ultimate Super Hosts Blacklist](https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/superhosts.deny.zip)
It is the same as this or a new repository?:
[Ultimate Hosts](https://hosts.ubuntu101.co.za/domains.list)
thanks

**Comment by mitchellkrogza** [comment]
Hi @maravento yes thats the same repo. If you look at the Readme on  https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist you can see the different raw files. The super hosts file is comprised of domain names plus IP addresses

**Comment by mitchellkrogza** [comment]
@maravento 

This Raw file is a plain text lists of domain names only
https://hosts.ubuntu101.co.za/domains.list

And this raw file is a plain text lists if bad IP's only
https://hosts.ubuntu101.co.za/domains.list

Those two lists have no commenting or anything and don't include the 0.0.0.0 domain.com or 0.0.0.0 IP.IP.IP.IP 

So for your uses pulling those might be easiest

**Comment by maravento** [comment]
please check the clarification. both links are the same

**Comment by mitchellkrogza** [comment]
Sorry working off my mobile

IP List only
https://hosts.ubuntu101.co.za/ips.list

Domains list only 
https://hosts.ubuntu101.co.za/domains.list

**Comment by maravento** [comment]
better. So, with your permission, we will include in the next update of [blackweb](https://github.com/maravento/blackweb), the new repositories:
https://hosts.ubuntu101.co.za/domains.list
https://raw.githubusercontent.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/master/dead-domains-ALL-combined.txt
https://raw.githubusercontent.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/master/whitelist-domains.txt
https://raw.githubusercontent.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/master/false-positives.txt

And in the [blackip](https://github.com/maravento/blackweb), the new repository:
https://hosts.ubuntu101.co.za/ips.list

**Comment by mitchellkrogza** [comment]
Absolutely no permission required and please let me know how it works out

**Comment by mitchellkrogza** [comment]
@maravento added a new whitelisted IP ranges file today > https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/blob/master/whitelisted-ip-ranges-ALL-combined.txt

**Comment by maravento** [comment]
Great. About ip.list
https://hosts.ubuntu101.co.za/ips.list
contains the following errors (which are not IPs/CIDR ipv4):
1035.globatel.ru
1570.info
1940s.org.uk
1945.net
2002:5bc8:c58::5bc8:c58
2002:b6ff:2c08::b6ff:2c08
2111dh.com
19333.com
21234.com
62528.com
14713804a.l2m.net
87654321.info

**Comment by maravento** [comment]
About whitelisted IPs/CIDR: https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/blob/master/whitelisted-ip-ranges-ALL-combined.txt

In our project [whiteip](https://github.com/maravento/whiteip/raw/master/whiteip.txt)

IPs/CIDR Add from Central-Repo:
199.30.16.0/24
199.30.27.0/24
203.208.60.0/24
64.68.80.0/21
157.56.0.0/14
207.46.0.0/16
the rest of the ips/cidr were already included in whiteip.txt

Problems detected in Central-Repo:
172.217.0.0/19 (should be 172.217.0.0/16)
NetRange:       172.217.0.0 - 172.217.255.255
CIDR:           172.217.0.0/16
NetName:        GOOGLE
NetHandle:      NET-172-217-0-0-1
Parent:         NET172 (NET-172-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       AS15169
Organization:   Google Inc. (GOGL)
RegDate:        2012-04-16
Updated:        2012-04-16
Ref:            https://whois.arin.net/rest/net/NET-172-217-0-0-1

66.249.64.0/18 and 66.249.80.0/20 (should be 66.249.64.0/19)
NetRange:       66.249.64.0 - 66.249.95.255
CIDR:           66.249.64.0/19
NetName:        GOOGLE
NetHandle:      NET-66-249-64-0-1
Parent:         NET66 (NET-66-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       
Organization:   Google Inc. (GOGL)
RegDate:        2004-03-05
Updated:        2012-02-24
Ref:            https://whois.arin.net/rest/net/NET-66-249-64-0-1

**Comment by mitchellkrogza** [comment]
Thanks @maravento I will merge these into the lists tomorrow

**Comment by mitchellkrogza** [comment]
@maravento Google IP Ranges amended in https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/commit/6cb387dd4f2da2e2e62b40fc44a9891c2551bc7a Other fixes for ips.list in progress

**Comment by maravento** [comment]
NetRange:       65.52.0.0 - 65.55.255.255
CIDR:           65.52.0.0/14
NetName:        MICROSOFT-1BLK
should remove:  65.52.104.0/24, 65.52.108.0/22, 65.55.213.0/24, 65.55.217.0/24, 65.55.24.0/24, 65.55.52.0/24, 65.55.55.0/24 (subnetwork of 65.52.0.0/14)

NetRange:       66.249.64.0 - 66.249.95.255
CIDR:           66.249.64.0/19
NetName:        GOOGLE
should remove:  66.249.80.0/20 (subnetwork of 66.249.64.0/19) and 66.249.64.0/18 (66.249.64.0/19 is a subnetwork of (A) 66.249.64.0/18)

NetRange:       172.217.0.0 - 172.217.255.255
CIDR:           172.217.0.0/16
NetName:        GOOGLE
should remove:  172.217.0.0/19 (subnetwork of 172.217.0.0/16)

NetRange:       131.253.21.0 - 131.253.47.255
CIDR:           131.253.21.0/24, 131.253.24.0/21, 131.253.32.0/20, 131.253.22.0/23
NetName:        MICROSOFT
should remove:  131.253.46.0/23 (subnetwork of 131.253.32.0/20)

NetRange:       108.177.0.0 - 108.177.127.255
CIDR:           108.177.0.0/17
NetName:        GOOGLE
should remove:  108.177.96.0/19, 108.177.8.0/21 (subnetwork of 108.177.0.0/17)

**Comment by mitchellkrogza** [comment]
Thanks @maravento please check latest commits at https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects and see if got it all correct now 👍

**Comment by maravento** [comment]
some CIDRs are already included in other CIDRs on your list. Example:
108.177.8.0/21 is a subnetwork of (B) 108.177.0.0/17
108.177.96.0/19 is a subnetwork of (B) 108.177.0.0/17
131.253.24.0/22 is a subnetwork of (A) 131.253.24.0/21
131.253.46.0/23 is a subnetwork of (B) 131.253.32.0/20
65.52.104.0/24 is a subnetwork of (B) 65.52.0.0/14
65.52.104.0/24 is a subnetwork of (B) 65.52.0.0/14
65.52.108.0/22 is a subnetwork of (B) 65.52.0.0/14
65.55.213.0/24 is a subnetwork of (B) 65.52.0.0/14
65.55.217.0/24 is a subnetwork of (B) 65.52.0.0/14
65.55.24.0/24 is a subnetwork of (B) 65.52.0.0/14
65.55.52.0/24 is a subnetwork of (B) 65.52.0.0/14
65.55.55.0/24 is a subnetwork of (B) 65.52.0.0/14
66.249.64.0/19 is a subnetwork of (A) 66.249.64.0/18
66.249.80.0/20 is a subnetwork of (B) 66.249.64.0/19
And I recommend:
172.217.0.0/16 instead of 172.217.0.0/19 (because NetRange: 172.217.0.0 - 172.217.255.255, CIDR: 172.217.0.0/16, NetName: GOOGLE)

**Comment by mitchellkrogza** [comment]
I gave updated all of these are you not seeing the updated files?
Current google-ip-ranges file is
```
108.177.0.0/17
172.217.0.0/16
173.194.0.0/16
2001:4860:4000::/36
203.208.60.0/24
207.126.144.0/20
209.85.128.0/17
216.239.32.0/19
216.58.192.0/19
2404:6800:4000::/36
2607:f8b0:4000::/36
2800:3f0:4000::/36
2a00:1450:4000::/36
2c0f:fb50:4000::/36
64.18.0.0/20
64.233.160.0/19
64.68.80.0/21
65.52.0.0/14
66.102.0.0/20
66.249.64.0/19
72.14.192.0/18
74.125.0.0/16
```

See > https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/blob/master/whitelist-google-ip-ranges.txt

**Comment by mitchellkrogza** [comment]
And current bing / microsoft ip ranges file is

```
131.253.21.0/24
131.253.22.0/23
131.253.24.0/21
131.253.24.0/22
131.253.32.0/20
157.54.0.0/15
157.56.0.0/14
157.60.0.0/16
199.30.16.0/24
199.30.27.0/24
207.46.0.0/16
40.112.0.0/13
40.120.0.0/14
40.124.0.0/16
40.125.0.0/17
40.74.0.0/15
40.76.0.0/14
40.80.0.0/12
40.96.0.0/12
65.52.0.0/14
```

https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/blob/master/whitelist-bing-ip-ranges.txt

**Comment by maravento** [comment]
Ah. ok. thanks
PD: when you update ip.list (https://hosts.ubuntu101.co.za/ips.list)

**Comment by mitchellkrogza** [comment]
Ok great, remember the CENTRAL REPO ip lists are for specific whitelisting only. Whereas https://hosts.ubuntu101.co.za/ips.list is a list of blacklisted IP addresses only. The https://hosts.ubuntu101.co.za/ips.list and all other RAW links on this Ultimate Hosts Repo are now updated automatically upon each build. You will see in about 3 minutes time all the RAW links on https://hosts.ubuntu101.co.za will all be the latest as a new build is in progress.

**Comment by mitchellkrogza** [comment]
I'm not 100% done with all the list cleaning functions on this repo which currently feed off CENTRAL REPO and strip out anything that's whitelisted. Almost done with all of those list cleaning functions.

**Comment by mitchellkrogza** [comment]
@maravento you will notice on latest build, hosts file is now under 1 million due to the list cleaning functions being pulled in from the ever growing CENTRAL REPO > https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist

**Comment by mitchellkrogza** [comment]
@xxcriticxx there are new RAW links for you, we are now < 1 million on hosts file.

**Comment by maravento** [comment]
I have problems with this list:
https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/blob/master/dead-domains-ALL-combined.txt
I can not identify its contents. I'm not sure if it's a **black or white domain list** (or something else). I see white or valid domains (such as jdownloader.org, disqus.com, etc) and also contains black or invalid domains (such as euroteen.org, etc.)
Could you clarify this? Thanks a lot

**Comment by mitchellkrogza** [comment]
@maravento those are all blacklisted domains but which during extensive testing came back as dead domains, no longer existent or no longer a web site there. As I said we about a 99% accuracy rate on dead domain testing and we use this to clean out dead domains from this repo. Every couple of weeks, that list of dead-domains will be re-tested for accuracy to confirm prior results and if any sites are active again they go back into a list of re-active-domains.

**Comment by mitchellkrogza** [comment]
Unfortunately TravisCI is horribly broken at the moment so all testing of lists has been halted until Travis fixes their problems.

**Comment by mitchellkrogza** [comment]
When I run builds on this repo, is strips out all dead domains, then it also strips out whitelisted domains and false positives to produce a hosts file that is not blocking valid sites.

**Comment by mitchellkrogza** [comment]
@maravento [CENTRAL REPO](https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects) was developed to address this earlier issue of yours 

`thanks for the info. I will update blackweb, but there is a problem. I would need the list of excluded domains to exclude them also from blackweb`

**Comment by maravento** [comment]
I get it. And I thank you and highly appreciate your effort to debug domains.
I give you a suggestion. I think it would be more "transparent" to have separate lists to avoid confusion. For example: a list of "dead, invalid or nonexistent" domains (separate from the "black or white" domains lists)
Perhaps the tool [httpstatus](https://httpstatus.io/) might be of great help to you.

**Comment by mitchellkrogza** [comment]
I am indeed in the process of splitting them into various different files with different error states, inactive, invalid, non existent, 404, 410 etc. It's a big work in progress and taking a lot of time but it's falling into place slowly but surely.

**Comment by mitchellkrogza** [comment]
Testing and re-testing lists with 1 million + domains takes some time.

**Comment by maravento** [comment]
Yes. A very long long time. good luck with that super task

**Comment by mitchellkrogza** [comment]
😬  I always bite off more than I chew .... but then I chew it up anyway. It's going to be a very critical repo for controlling cleaning up all the rubbish from other lists and within a few weeks I think it will be in a good state, it's already helped reduce Ultimate's hosts list to < 1 million

**Comment by mitchellkrogza** [comment]
When I'm done I should have some source control on dead domains like this:

dead-domains-404.txt
dead-domains-410.txt
dead-domains-blogspot.txt
dead-domains-liveadvert.txt
dead-domains-free.fr.txt
dead-domains-wordpress-blogs.txt
dead-domains-inactive.txt
dead-domains-invalid.txt
dead-domains-expired.txt

and possibly more categories 

and then have them all combined into the dead-domains-ALL-combined.txt file

**Comment by maravento** [comment]
from the point of view of users, so many categories can create confusion. From my point of view (personal) i think it is not necessary to create so many categories (you would have more workload and you would need to give more explanations to users). 
I think you could summarize it in:
invalids
inactive/expired
Putting these different categories together in one file (dead-domains-ALL-combined.tx) is not a very good idea... but it's your project, so you decide

**Comment by mitchellkrogza** [comment]
Thanks @maravento certainly appreciate your insight and I honestly want to keep it simple and effective so your approach sounds more plausible. I'll still keep the dead blogspot,wordpress,free.fr lists and others in a separate folder as they go through a completely different test process which determines 100 % that they truly don't exist anymore. I'll figure out a nice solution and try keep it simple

**Comment by maravento** [comment]
The [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) always works better than the hard way.

**Comment by maravento** [comment]
A suggestion. it is easier to read IPs / CIDR lists this way.
Example:
https://raw.githubusercontent.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/master/whitelist-bing-ip-ranges.txt
131.253.21.0/24
131.253.22.0/23
131.253.24.0/21
131.253.24.0/22
131.253.32.0/20
157.54.0.0/15
157.56.0.0/14
157.60.0.0/16
199.30.16.0/24
199.30.27.0/24
207.46.0.0/16
40.112.0.0/13
40.120.0.0/14
40.124.0.0/16
40.125.0.0/17
40.74.0.0/15
40.76.0.0/14
40.80.0.0/12
40.96.0.0/12
65.52.0.0/14
Command: sort -o whitelist-bing-ip-ranges.txt -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n whitelist-bing-ip-ranges.txt
Result:
40.74.0.0/15
40.76.0.0/14
40.80.0.0/12
40.96.0.0/12
40.112.0.0/13
40.120.0.0/14
40.124.0.0/16
40.125.0.0/17
65.52.0.0/14
131.253.21.0/24
131.253.22.0/23
131.253.24.0/21
131.253.24.0/22
131.253.32.0/20
157.54.0.0/15
157.56.0.0/14
157.60.0.0/16
199.30.16.0/24
199.30.27.0/24
207.46.0.0/16

**Comment by mitchellkrogza** [comment]
Thanks @maravento fixed in https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/commit/5882b628a68576c425a77a0f5f8dc32c319ba40b have a look.

**Comment by mitchellkrogza** [comment]
@maravento I added better sorting to this list > https://hosts.ubuntu101.co.za/ips.list

using the following 

`sort -o $_combinedips -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n -k 5,5n -k 6,6n -k 7,7n -k 8,8n -k 9,9n $_combinedips`

But does not seem correct. You maybe got a better sort for this ????

**Comment by mitchellkrogza** [comment]
@maravento never mind I fixed it, had my sort in the wrong place in my script, I also added the `-u` flag so now `sort -o $_input2 -u -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n -k 5,5n -k 6,6n -k 7,7n -k 8,8n -k 9,9n $_input2` produces a much better formatted list >>> https://hosts.ubuntu101.co.za/ips.list

Thank you again for your wonderful sorting command line for IP's, it's a great and much needed addition and improvement to the repo.

**Comment by maravento** [comment]
It is not recommended to use -u (sort -u) because, for example, the following may happen:
131.253.24.0/21
131.253.24.0/22
sort -u
result
131.253.24.0/21
(delete the second line)
Then it is better to do sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n -k 5,5n -k 6,6n -k 7,7n -k 8,8n -k 9,9n list | uniq > newlist

**Comment by mitchellkrogza** [comment]
Awesome, thanks a mil, busy running a new build now to test that.

**Comment by mitchellkrogza** [comment]
@maravento please check now if the list looks better / correct > https://hosts.ubuntu101.co.za/ips.list

I used the following
`sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n -k 5,5n -k 6,6n -k 7,7n -k 8,8n -k 9,9n $_input2 | uniq > $_input4 && mv $_input4 $_input2`

**Comment by mitchellkrogza** [comment]
also added better sorting to https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/blob/master/whitelisted-ip-ranges-ALL-combined.txt

**Comment by maravento** [comment]
A suggestion. Separate ipv4 and ipv6 lists

**Comment by mitchellkrogza** [comment]
:+1: @maravento shall implement tomorrow

**Comment by mitchellkrogza** [comment]
@maravento have we got a better layout now on CENTRAL REPO ?? Have a look and give me some feedback please. https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects

**Comment by mitchellkrogza** [comment]
Once you guys both happy, I can re-write the cleaning functions on all my other repo's including this one of course.

**Comment by maravento** [comment]
I think you have done a great job of debug and reorganizing. i congratulate you

**Comment by mitchellkrogza** [comment]
Thanks so much @maravento much appreciated and truly appreciate all your input . Have a great weekend

**Comment by maravento** [comment]
Hi. 
Aobut: https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/blob/master/DOMAINS-dead.txt
I was doing a random routine review and I have seen some valid and active url (porn) such as:
http://yoursexymind.com/
http://09zyy.com/
https://www.zurich-girls.ch/
It can happen that a malicious domain (porn, weapons, etc.) is inactive for a while and then reactivated.
So, in these cases, I'd think it's best to block them, regardless of whether the domain is active or not

**Comment by mitchellkrogza** [comment]
Thanks @maravento all those lists are currently undergoing re-testing. We will soon have them fixed and keep certain domains on the list regardless of if their state changes. It's a big Work in progress this one.

**Comment by mitchellkrogza** [comment]
I think this is where we will use https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/blob/master/DOMAINS-re-active.txt to keep a list of permanently blacklisted domains and also add to it from our re-tests when previously inactive are now active again.

**Comment by maravento** [comment]
that's too much debugging work

**Comment by mitchellkrogza** [comment]
Gotta re-think this whole thing a bit.

**Comment by maravento** [comment]
I give you the same suggestion I gave you days ago: 
You already have a blacklist (https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist)
Then debug that list, not with dead domains (because they can revive). Debug it with invalid domains (which do not exist or never existed).
Take a look at our list of invalid domains (hopefully more complete):
https://github.com/maravento/blackweb/blob/master/invalid.txt

**Comment by mitchellkrogza** [comment]
@maravento thanks going to take a fresh start with the dead domains control manner on central repo. As always appreciate your input and help. :+1:

**Comment by mitchellkrogza** [comment]
@maravento I took a fresh start to CENTRAL REPO now, focusing mostly on dead blogspot domains which we know 100% are dead and the list of invalid domains. Now a much smaller list of dead domains and will just focus on invalid domains. https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects

**Comment by maravento** [comment]
I have tried the new version of DOMAINS-dead.txt and it goes perfect (I have verified the domains and they are really dead or invalid). I included it in the next update of [Blackweb](https://github.com/maravento/blackweb/raw/master/invalid.txt) 
PD: I've been debugging Blackweb for 2 days with DOMAINS-dead.txt ... and counting ... Our work never ends. 
Thanks for your great work

**Comment by mitchellkrogza** [comment]
Thanks so much @maravento and thanks again for your valuable insight and help. It's now a much smaller list and re-testing it will only ever take a few hours. I have some tests running on the complete Ultimate hosts list which will give us some additional invalid domains which will be tested once more before being added to domains-invalid. 👍

**Comment by maravento** [comment]
Hi. @mitchellkrogza There are many duplicate IPs / CIDRs in the **ips.list**. This happens because many lines have a space at the end and generate duplicates. Example:
222.187.221.28
222.236.44.131
223.165.25.36
.... A very long etc
So, to fix it, debug the list with:
sort -t. -k 1.1n -k 2.2n -k 3,3n -k 4,4n -k 5,5n -k 6,6n -k 7,7n -k 8,8n -k 9,9n ips.list | sed 's / * $ //' | uniq> newips.list
after debugging, you will also notice that there are other conflicts. Example:
216.152.252.253 is a subnetwork of (B) 216.152.240.0/20
.... A long etc
But that is not serious. I solve it with this [script](http://stackoverflow.com/a/35114656/3776858),(it takes days to debug)

**Comment by mitchellkrogza** [comment]
Thank @maravento I found the problem, was only one of the input sources yoyo.org which had spaces. All spaces removed and new build in progress.

**Comment by maravento** [comment]
i found in ips.list:
2002:3f8d:ec63:0:0:0:3f8d:ec63
2002:5bc8:c58::5bc8:c58
2002:b6ff:2c08::b6ff:2c08
2002:b6ff:2d90::b6ff:2d90
is Ipv4 & ipv6 or ipv4 only?

**Comment by mitchellkrogza** [comment]
Thanks @maravento currently ips.list is combined ipv4 and ipv6 and also needs better sorting which I will do tomorrow. I will also address those reserved ranges. Can you spot any more dupes?

**Comment by mitchellkrogza** [comment]
I think all those reserved IP ranges originate from the yoyo.org input source. Will have it sorted tomorrow.

**Comment by maravento** [comment]
I think that's all

**Comment by maravento** [comment]
I recommend using this pipe to discard anything unusual (ipv6, spaces...):
sed 's/^[ \s]*//;s/[ \s]*$//' | sed "/:/d"
