### ISSUE TITLE
en.bab.la

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#64]
::: /etc/pihole/list.41.hosts.ubuntu101.co.za.domains (1 results)
0.0.0.0 en.bab.la

The bab.la dictionaries will help you find the right translation for any word in the foreign language you are learning.

**Comment by mitchellkrogza** [comment]
@xxcriticxx all fixed in latest builds. Thanks for your contributions. :+1:
