### ISSUE TITLE
disqus.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#65]
disqus still getting blocked on something maybe on `0.0.0.0 www.disqus.com`

**Comment by funilrys** [comment]
#57 :thinking:

**Comment by mitchellkrogza** [comment]
@xxcriticxx please test now with latest updates. There's a couple of other domains that disqus is reliant on which were also blocked. And should be fixed now. Please confirm. @funilrys latest fix should sort this now 🙏

**Comment by xxcriticxx** [comment]
@mitchellkrogza ok i check when i get home

**Comment by mitchellkrogza** [comment]
Cool let me know if all ok now. :+1:

Kind Regards
Mitchell Krog
**************************************************
Visit me at https://mitchellkrog.com
**************************************************
License My Images From Getty Images Here
<http://www.gettyimages.com/search/photographer?family=creative&page=1&photographer=mitchell%20krog&sort=best&excludenudity=true#license>

or From Gallo Images Here
<http://galloimages.co.za/Search?q=mitchell%20krog&p=1&a=1&l=2,1&st=2&dr=on&is=1&token=48034&pp=13&rc=6>
**************************************************

**Comment by xxcriticxx** [comment]
disqus.com now works!

@mitchellkrogza whats the list of domains i will add to pihole whitelist

**Comment by mitchellkrogza** [comment]
That’s great news. You should always reference the centralized whitelist of
domains from

https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/blob/master/DOMAINS-whitelist.txt

**Comment by xxcriticxx** [comment]
@mitchellkrogza i need to know what you guys whitelisted to get disqus.com to work

**Comment by mitchellkrogza** [comment]
Have a look at the commits on CENTRAL REPO
https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/commit/1d182f4186fa24b3f71a4548de85823f247314c9
 AND
https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/commit/733d89f5bf58b0985eb88e255c00ea64c60649db

**Comment by mitchellkrogza** [comment]
Some interesting developments https://thehackernews.com/2017/10/disqus-comment-system-hacked.html?https=1

**Comment by funilrys** [comment]
Even better : https://www.troyhunt.com/disqus-demonstrates-how-to-do-data-breach-disclosure-right/
