### ISSUE TITLE
Diagnosing False Positives and Blocked Sites - HOW TO 

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Ultimate.Hosts.Blacklist#66]
If you ever pick up a false positive site that is being blocked by this hosts list. Please open the affected web site, click on VIEW > Developer > Developer Tools and make sure you are on the SOURCES tab. This will quickly reveal which sources on the page are being blocked and you can then report all those resources along with your false positive ISSUE or a simple screen grab as below. This will us quickly attend to whitelisting and fixing things properly and for good.

![screen shot 2017-10-01 at 2 25 50 pm](https://user-images.githubusercontent.com/9961541/31054530-9f16e8ea-a6b4-11e7-947f-cac6eeaad692.png)

@xxcriticxx

**Comment by xxcriticxx** [comment]
add this to wiki page

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx as you can see the Wiki pages are non existent so I will get them set up tomorrow with some basic info and Q’s and A’s and would also appreciate one done if you can contribute to them to answer all those little niggly questions people have.

**Comment by xxcriticxx** [comment]
@mitchellkrogza pihole recommends using this plugin 

https://chrome.google.com/webstore/detail/dnsthingy-assistant/fdmpekabnlekabjlimjkfmdjajnddgpc?hl=en

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx will check it out tomorrow

Kind Regards
Mitchell Krog
**************************************************
Visit me at https://mitchellkrog.com
**************************************************
License My Images From Getty Images Here
<http://www.gettyimages.com/search/photographer?family=creative&page=1&photographer=mitchell%20krog&sort=best&excludenudity=true#license>

or From Gallo Images Here
<http://galloimages.co.za/Search?q=mitchell%20krog&p=1&a=1&l=2,1&st=2&dr=on&is=1&token=48034&pp=13&rc=6>
**************************************************
