### ISSUE TITLE
nocoin list 

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#67]
this is maybe something worth adding

https://github.com/hoshsadiq/adblock-nocoin-list

**Comment by mitchellkrogza** [comment]
Thanks @xxcriticxx will check it out in the morning

**Comment by SMed79** [comment]
Update
```
crypto-loot.com
ppoi.org
projectpoi.com
webmine.cz
```

**Comment by mitchellkrogza** [comment]
Thanks @SMed79 added to my latest build. :+1:
