### ISSUE TITLE
Whitelisting Suggestions

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#68]
https://wally3k.github.io/

**Comment by funilrys** [comment]
Well, knowing the serious of @wally3k I can only support :+1:

**Comment by mitchellkrogza** [comment]
Whitelisted those domains in CENTRAL REPO, any occurence of them in current build of this repo will be stripped out. 👍

**Comment by mitchellkrogza** [comment]
Implemented in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/461665bd3f01c711c116c9aa68b522a9fe1138a9
