### ISSUE TITLE
parked domains

### ISSUE THREAD

**Issue by SMed79** [mitchellkrogza/Ultimate.Hosts.Blacklist#78]
Hi,

all the [domains parked](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/files/1385155/parked.txt) via `parkingcrew.com` are used to serve ads/popup.

e.g: 
- nsfw sites: `http://i.imgur.com/zZbN4OQ.png`
- random script name: http://&#8203;bokepabc.com/**mitchellkrogza**.js

**Comment by mitchellkrogza** [comment]
Thanks @SMed79 source added and build in progress.

**Comment by mitchellkrogza** [comment]
Appreciate your contributions greatly 👍 all your input sources you have pointed me to are all in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/tree/master/.input_sources/_SMed79
