### ISSUE TITLE
money.cnn.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#8]
because of

```
ALL: money.cnn.com/2015/05/22/technology/adult-friendfinder-hacked
ALL: money.cnn.com/2015/05/27/technology/cross-dresser-adult-site-hack
```

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/fcaa791f48194829bd090e8a15d87bb4de6b0e1d

**Comment by funilrys** [comment]
@xxcriticxx can you confirm if this is still present? :thinking:
