### ISSUE TITLE
gatekeeper.tss.net

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#81]
@mitchellkrogza or @funilrys what is this domain used for? my pihole went crazy on it. when was this added?

**Comment by mitchellkrogza** [comment]
@xxcriticxx what do you mean it went crazy? I will have to see which input source this came from.

**Comment by mitchellkrogza** [comment]
@xxcriticxx it comes in from this source

 https://raw.githubusercontent.com/eladkarako/hosts.eladkarako.com/master/build/hosts_adblock.txt

**Comment by mitchellkrogza** [comment]
```
./_HOSTS_AdBlock/domains.txt:cdn.gatekeeper.tss.net
./_HOSTS_AdBlock/domains.txt:gatekeeper.tss.net
./_HOSTS_AdBlock/domains.txt:www.gatekeeper.tss.net
```

**Comment by xxcriticxx** [comment]
what is this domain used for? my pihole block about 2000 connections from domain

**Comment by xxcriticxx** [comment]
google vaguely talks that this maybe spyware so i need to know if should worry or not

**Comment by mitchellkrogza** [comment]
Can you install `rkhunter` on your Pi and make sure everything is OK and it has never been compromised.

**Comment by mitchellkrogza** [comment]
Possibly even also scanning with clam too

**Comment by mitchellkrogza** [comment]
@xxcriticxx not sure if this is related or not > https://forums.malwarebytes.com/topic/191746-removal-instructions-for-tss-vince/

**Comment by mitchellkrogza** [comment]
@xxcriticxx it is malware > Trojan Kuluoz --- See: http://www.malwareurl.com/ns_listing.php?as=AS7385

**Comment by mitchellkrogza** [comment]
I suggest inspecting all your PC's, phones, tablets on your network very carefully to see if one of them is infected. Trojan seems aimed at Windoze systems so I would start there if you have any.

**Comment by xxcriticxx** [comment]
i got pihole running on regular pc not pie3

**Comment by xxcriticxx** [comment]
any recommendation on program?

**Comment by mitchellkrogza** [comment]
Suggestion to download one or more of these bootable live antivirus / malware CD's and check the pc is not infected > https://www.lifewire.com/free-bootable-antivirus-tools-2625785

**Comment by xxcriticxx** [comment]
let me try first see what malwarebytes finds. then i go for live cd for deeper cleaning.

**Comment by SMed79** [comment]
> let me try first see what malwarebytes finds.

Check also using **AdwCleaner** https://www.malwarebytes.com/adwcleaner/

**Comment by xxcriticxx** [comment]
@SMed79 thats part of malwarebytes now right?

**Comment by xxcriticxx** [comment]
we still dont know what it is lets hope i find it 

this connection for right now

![capture](https://user-images.githubusercontent.com/15007183/31672843-9ae664e8-b32b-11e7-9fc3-0b60863cedb8.PNG)

**Comment by xxcriticxx** [comment]
4 connections every 5 minutes or so

```
Oct 17 11:18:18 dnsmasq[4737]: /etc/pihole/gravity.list gatekeeper.tss.net is 192.168.1.131
Oct 17 11:18:18 dnsmasq[4737]: /etc/pihole/gravity.list gatekeeper.tss.net is 192.168.1.131
Oct 17 11:18:18 dnsmasq[4737]: /etc/pihole/gravity.list gatekeeper.tss.net is 192.168.1.131
Oct 17 11:18:18 dnsmasq[4737]: /etc/pihole/gravity.list gatekeeper.tss.net is 192.168.1.131
```

**Comment by xxcriticxx** [comment]
@funilrys this send every 5 min i dont think connection would stay open that long

**Comment by funilrys** [comment]
@xxcriticxx Well with `netstat -b 5 >> C:\connections.txt` you can set the timeout (in this example 5 seconds)

**Comment by xxcriticxx** [comment]
@funilrys i still dont know what am looking for gatekeeper ip?

**Comment by funilrys** [comment]
Yes repeating IP (from gatekeeper) then you get the PID of the programm :)

Once you got the PID you can get the program name with something like `tasklist /fi "pid eq PIDOFTHEPROGRAM"` (I used that only once in my life and it wasn't in the most recent build of Windows 😹 )

**Comment by xxcriticxx** [comment]
its going be very funny if i dont find shit

**Comment by xxcriticxx** [comment]
3 hr of scanning and found nothing :(

**Comment by xxcriticxx** [comment]
@mitchellkrogza any order ideas How to catch this something

**Comment by xxcriticxx** [comment]
@funilrys netstat only shows local ip not external

**Comment by mitchellkrogza** [comment]
No idea, truly sounds like something is hiding on your pc and hiding itself real good. How many of those different bootable virus scan discs have you tried?

**Comment by funilrys** [comment]
@xxcriticxx No ... I think you need a deep cleaning ... Cause the command I said give Remote adress not local adress ...

**Comment by xxcriticxx** [comment]
Zero am going try them today. I scanned my win pc and found only tracking cookies

**Comment by mitchellkrogza** [comment]
**VITAL VITAL VITAL** that you scan with a bootable virus and malware scanner CD, you cannot scan from inside the system at all, these things are FAR too clever and will hide themselves from every single scanner

**Comment by xxcriticxx** [comment]
Ok will do that today

Only if I knew what ip that used on the inside of the network then I would have less computers to scan

**Comment by mitchellkrogza** [comment]
It would never reveal that because the malware is simply trying to contact tss.gatekeeper.net using your local IP that's all.

**Comment by mitchellkrogza** [comment]
how many PC's do you have on your network?? Turn everything off. Then turn one on and watch, then turn it off. Then turn next one on and watch. Keep doing this until you find which PC or device is infected

**Comment by xxcriticxx** [comment]
few computers 6 maybe but i have lots iot devices (thermostats, fire alarm, cams)

**Comment by mitchellkrogza** [comment]
Going to be a long day for you when you get home, turn everything off and I mean everything and follow what I said to find what device is infected. Any IOT device could be easily infected, people's "intelligent" fridges and washing machines get hacked daily.

**Comment by mitchellkrogza** [comment]
Most IOT devices are horribly insecure ie. NO SECURITY at all

**Comment by mitchellkrogza** [comment]
Have you upgraded your wifi router firmware also agains the KRACK / WPA2 flaw ???

**Comment by xxcriticxx** [comment]
no i am on dd wrt firmware

**Comment by mitchellkrogza** [comment]
Have you confirmed you have latest version and that it's not vulnerable to the NOONCE WPA2 flaw?

**Comment by xxcriticxx** [comment]
no i see ip connected to my router everything from inside the house

**Comment by mitchellkrogza** [comment]
That's great but understand with the KRACK flaw it's a MITM technique used to steal data from your wifi network without you knowing or without the person even connecting to your network, simply sitting in the middle scanning anything that's not encrypted.

**Comment by xxcriticxx** [comment]
yes this home network nothing major here 

should i try wireshark?

**Comment by mitchellkrogza** [comment]
For now stay focused, don't go wasting time with wireshark. Check one device at a time as I described above, that's the only way you are going to find what device is doing that.

**Comment by xxcriticxx** [comment]
ok eveything is off looking on my pihole log for gatekeeper

**Comment by xxcriticxx** [comment]
@mitchellkrogza well its not windows related only machine on is pihole and i just got it in the logs

**Comment by mitchellkrogza** [comment]
So what are you running your pihole on ? windows ?

**Comment by xxcriticxx** [comment]
ubuntu 16.04

**Comment by mitchellkrogza** [comment]
Ok .... do you have `rkhunter` installed?

**Comment by xxcriticxx** [comment]
what should i do with sleeping latops? turn them off?

**Comment by mitchellkrogza** [comment]
Everything OFF, everything 100% off not in sleep mode or anything

**Comment by mitchellkrogza** [comment]
Even your phone, tablets .... every single little thing that connects to your wifi

**Comment by mitchellkrogza** [comment]
Then monitor your pihole

**Comment by xxcriticxx** [comment]
ok everything that could be off is off

**Comment by xxcriticxx** [comment]
ok still there only pihole on and iot on

going install hunter and clam

**Comment by mitchellkrogza** [comment]
OK so ONLY your Ubuntu box running the pihole is on? Correct?

**Comment by mitchellkrogza** [comment]
so now

```
sudo apt-get install rkhunter
sudo rkhunter --update
sudo rkhunter --propupd
sudo rkhunter -c --enable all --disable none
```

**Comment by mitchellkrogza** [comment]
Then 

```
sudo apt-get install clamav
sudo freshclam
sudo clamscan -ri --exclude-dir=^/sys\|^/proc\|^/dev /
```

Then to scan whole system including removing anything infected

`sudo clamscan -r --remove /`

**Comment by xxcriticxx** [comment]
rkhunter https://pastebin.com/NG00tQim

**Comment by xxcriticxx** [comment]
```
critic@critic:~$ sudo freshclam
ERROR: /var/log/clamav/freshclam.log is locked by another process
ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
```

**Comment by mitchellkrogza** [comment]
Reboot then run freshclam again

**Comment by mitchellkrogza** [comment]
rkhunter results look ok to me

**Comment by xxcriticxx** [comment]
same problem after reboot

```
critic@critic:~$ sudo freshclam
[sudo] password for critic: 
ERROR: /var/log/clamav/freshclam.log is locked by another process
ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
critic@critic:~$ 
```

**Comment by mitchellkrogza** [comment]
Try this

```
sudo service clamav-daemon stop
sudo service clamav-freshclam stop
sudo freshclam
sudo service clamav-daemon start
sudo service clamav-freshclam start

```

**Comment by xxcriticxx** [comment]
```
critic@critic:~$ sudo service clamav-daemon stop
Failed to stop clamav-daemon.service: Unit clamav-daemon.service not loaded.
critic@critic:~$ sudo service clamav-freshclam stop
critic@critic:~$ sudo freshclam
ClamAV update process started at Wed Oct 18 10:31:21 2017
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd is up to date (version: 23963, sigs: 1756614, f-level: 63, builder: neo)
bytecode.cvd is up to date (version: 313, sigs: 73, f-level: 63, builder: neo)
critic@critic:~$ sudo service clamav-daemon start
Failed to start clamav-daemon.service: Unit clamav-daemon.service not found.
critic@critic:~$ sudo service clamav-freshclam start
```

**Comment by mitchellkrogza** [comment]
```
sudo systemctl enable clamav-daemon.service
systemctl status clamav-daemon.service
sudo service clamav-daemon restart
```

**Comment by xxcriticxx** [comment]
```
critic@critic:~$ sudo systemctl enable clamav-daemon.service
[sudo] password for critic: 
Failed to execute operation: No such file or directory
```

**Comment by mitchellkrogza** [comment]
Try

```
sudo /etc/init.d/clamav-daemon stop
sudo freshclam -v
sudo /etc/init.d/clamav-daemon start
```

**Comment by mitchellkrogza** [comment]
This already shows that freshclam did update earlier

```
critic@critic:~$ sudo service clamav-daemon stop
Failed to stop clamav-daemon.service: Unit clamav-daemon.service not loaded.
critic@critic:~$ sudo service clamav-freshclam stop
critic@critic:~$ sudo freshclam
ClamAV update process started at Wed Oct 18 10:31:21 2017
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd is up to date (version: 23963, sigs: 1756614, f-level: 63, builder: neo)
bytecode.cvd is up to date (version: 313, sigs: 73, f-level: 63, builder: neo)
critic@critic:~$ sudo service clamav-daemon start
Failed to start clamav-daemon.service: Unit clamav-daemon.service not found.
critic@critic:~$ sudo service clamav-freshclam start
```

So now just run

`sudo clamscan -ri --exclude-dir=^/sys\|^/proc\|^/dev /`

**Comment by xxcriticxx** [comment]
let me look in that log file

```
critic@critic:~$ sudo freshclam -v
ERROR: /var/log/clamav/freshclam.log is locked by another process
ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
critic@critic:~$ sudo /etc/init.d/clamav-daemon start
```

**Comment by xxcriticxx** [comment]
looks like we need to make conf file

https://pastebin.com/4bzjn2Wa

**Comment by mitchellkrogza** [comment]
Just try run `sudo clamscan -ri --exclude-dir=^/sys\|^/proc\|^/dev /` and see if it works

**Comment by xxcriticxx** [comment]
conf file is there

**Comment by xxcriticxx** [comment]
nothing happens only blinking cursor

**Comment by mitchellkrogza** [comment]
remove it and reinstall it.

`sudo apt-get remove --purge clamav` and then try again.

First do a

```
sudo apt-get update
sudo apt-get upgrade
```

before reinstalling clamav

**Comment by xxcriticxx** [comment]
same error msg as before

**Comment by mitchellkrogza** [comment]
Ok forget about the fresh clan error can you run clamscan command I gave you?

**Comment by mitchellkrogza** [comment]
Most importantly you say everything is turned off and ONLY your Ubuntu box with the pihole is on and on the network? 

Am I correct? 

If so are you still seeing those connections to tss.gatekeeper.net ???

**Comment by xxcriticxx** [comment]
only ubuntu computer that has pihole is online and iot stuff i cant turn off 

yes i still have connection to `gatekeeper.tss.net`

**Comment by xxcriticxx** [comment]
got to work scanning /home found 1 infected file

----------- SCAN SUMMARY -----------
Known viruses: 6317227
Engine version: 0.99.2
Scanned directories: 2066
Scanned files: 18831
Infected files: 1
Total errors: 2
Data scanned: 1160.25 MB
Data read: 709.78 MB (ratio 1.63:1)
Time: 294.024 sec (4 m 54 s)

**Comment by mitchellkrogza** [comment]
Read the clam log file to see what file is infected, then either manually delete it or run clam with the clean option I posted earlier on

**Comment by xxcriticxx** [comment]
i dont have log file i think i have run and save to txt file

**Comment by mitchellkrogza** [comment]
Look in your /var/log directory it definitely creates a log file

**Comment by xxcriticxx** [comment]
yes but nothing there about what file is infected

**Comment by xxcriticxx** [comment]
going try something like this 

`sudo clamscan -r /home | grep FOUND >> /home/critic/Desktop/report/report.txt`

**Comment by xxcriticxx** [comment]
ok this works going do rest of computer now

**Comment by xxcriticxx** [comment]
file removed gatekeeper still in the logs

**Comment by mitchellkrogza** [comment]
My only solution and honest advice would be a clean slate. Wipe the box and reinstall Ubuntu. I would not honestly go any further not knowing my main Ubuntu box has a problem. Sorry not good news but that is what I would do personally.

**Comment by xxcriticxx** [comment]
i dont think its ubuntu or windows its one of the iot calling home

**Comment by mitchellkrogza** [comment]
But they were all turned off NO?

**Comment by mitchellkrogza** [comment]
I can’t be any clearer 

1. Turn off everything 
2. Only have Ubuntu box running with pihole and monitor to see if any connections to gatekeeper
3. If NONE then turn on one device and ONE device only and monitor to see if there are any connections to gatekeeper. 
4. If None, turn off device
5. Turn on next device and monitor to see if any connections to gatekeeper

Leave each device up and running for at least 10-20 minutes while monitoring but then shut it down again before testing next one.

This takes time and patience and is the ONLY way you will find the infected device.

**Comment by xxcriticxx** [comment]
@mitchellkrogza i cant turn off fire alarms and thermostats they dont have off option 

everything that could off been turn off was turn off

**Comment by mitchellkrogza** [comment]
@funilrys any ideas here? This is showing the real downside of IOT devices and how problematic they can be and potential dangers of insecure ones

**Comment by xxcriticxx** [comment]
@funilrys asleep by now by this long post

**Comment by funilrys** [comment]
Hello guys, 

Let me resume a bit ...

- Pi-Hole detect outgoing connection to that domain
- After all machine has been taking down only ubuntu (pi-hole) get the log

So if we are at that level, we have 2 options, monitor all the home or monitor each machine to find which one is "infected" 

So in ubuntu, it's simple if it's an outgoing connection:
```
$  netstat -cnputw
```
give us a real-time outgoing connection (from that machine)

For other machines it depends if you know the system and has access to them. Otherwise for the second point, to monitor all the house we need to understand how your router is set up which information we don't have if I read right ...

P.S Is Pi-Hole connected directly to the router or is it the router? :thinking:

**Comment by xxcriticxx** [comment]
Pihole is plugin one of the ports on the back of the router

Pihole ip is enter I dhcp field in the router

**Comment by xxcriticxx** [comment]
@funilrys can we save this to txt file?

**Comment by mitchellkrogza** [comment]
@xxcriticxx you can also see all connected devices on your network by running `nmap -sP 192.168.1.1/24` if your network IP addressing is different like 10.0.0.1 etc just change the command line to `nmap -sP 10.0.0.1/24`

**Comment by funilrys** [comment]
Well you can keep it runing and output with `>> output` at the end of the command !

**Comment by xxcriticxx** [comment]
I will try both shortly

**Comment by xxcriticxx** [comment]
nmap only gives me list of my current clients not where they connect

**Comment by xxcriticxx** [comment]
i think am going have to use pihole dhcp in order to assign ip to my clients so i can see what connects where

**Comment by mitchellkrogza** [comment]
@xxcriticxx probably a good idea. Does piHole (sorry never used it) not show you all local IP's and where they are connecting to ?

**Comment by xxcriticxx** [comment]
Not right now. Router does dhcp right now. I have switch it around and let pihole do it.

**Comment by mitchellkrogza** [comment]
Great, keep us updated and really hope you find the culprit.

**Comment by xxcriticxx** [comment]
plus i need to format few system as they are supper slooooooooooooooooow

@mitchellkrogza you can install pihole on most linux system i recommend for weekend project

**Comment by mitchellkrogza** [comment]
@xxcriticxx 

![screen shot 2017-11-03 at 12 31 28 pm](https://user-images.githubusercontent.com/9961541/32369739-0cafa8ae-c093-11e7-87ae-203d3f9f7f24.png)

**Comment by xxcriticxx** [comment]
@mitchellkrogza please provide me link to this article

**Comment by mitchellkrogza** [comment]
https://youtu.be/Op0tHjExST8 subscribe to their channel they talk a lot about IOT device hacking. 

This one might also interest you 

https://motherboard.vice.com/en_us/article/aekj9j/internet-of-things-ransomware-smart-thermostat

**Comment by xxcriticxx** [comment]
`db.local.clamav.net 514`

clamav calls home over 500 in last hour probably update out

**Comment by eladkarako** [comment]
@mitchellkrogza / @xxcriticxx 
don't know if it's relevant anymore but if you're still need to use those ad-blocking lists,
the links got updated, <a href="http://hosts.eladkarako.com/">GitHub hosted</a>.

<pre>
<em>HOSTS (AdBlock format for browser)</em>
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock.txt

<sub>also..
HOSTS (native HOSTS format)
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts0.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_with_localhost.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts0_with_localhost.txt

AdBlock lists
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block_inline_script.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_hide.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_style_inject.txt
</sub>
</pre>

**Comment by funilrys** [comment]
@eladkarako Is there any recommendation out there? Cause I read elsewhere:

> **I don't recommend adding/using ANY those list anywhere anymore.**

**Comment by eladkarako** [comment]
@funilrys
<a href="https://github.com/StevenBlack/hosts/issues/359#issuecomment-314650772">Yep</a>, The lists are known to be somewhat strict (they are designed in net.admins in mind), basically if they used to work well for you before, keep on using them, using the direct links <a href="https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/81#issuecomment-364438433">from above</a>. I advice using <code>hosts0.txt</code> and appending it to your machine's <a href="https://en.wikipedia.org/wiki/Hosts_(file)"><code>HOSTS</code>-file</a>, it will take care of machine-wide malicious requests, following with installing <a href="https://github.com/gorhill/uBlock/releases">uBlock origin</a> (instead of any/all other AdBlock extension) on your browsers, and using <code>hosts_adblock.txt</code>, which will prevent the delay usually caused by DNS-resolving error, blocking requests before even a connection is opened.
Optionally use the rest of the lists with any combination of your favourite 3<sup>rd</sup>-party ad-blocking lists..
..and maybe <a href="https://en.wikipedia.org/wiki/PeerBlock">PeerBlock</a> too..
