### ISSUE TITLE
New CoinBlockerLists

### ISSUE THREAD

**Issue by ZeroDot1** [mitchellkrogza/Ultimate.Hosts.Blacklist#90]
Simple lists that can help prevent cryptomining in the browser or other applications.
https://github.com/ZeroDot1/CoinBlockerLists
I hope you can use it.

**Comment by SMed79** [comment]
Do you have examples of sites which embed these domains not already blocked in [NoCoin adblock list](https://github.com/hoshsadiq/adblock-nocoin-list/)?

**Comment by mitchellkrogza** [comment]
Thanks @ZeroDot1 have added this source, the hosts file generator will take care of any duplicates between the other coinblocker list from @SMed79

**Comment by ZeroDot1** [comment]
Thanks for using the list :)

**Comment by ZeroDot1** [comment]
![bildschirmfoto_2017-10-22_18-13-10](https://user-images.githubusercontent.com/28985171/31863902-b8cdaeb2-b754-11e7-8737-a10ed12775da.png)

**Comment by mitchellkrogza** [comment]
:+1: I will update Readme tomorrow to credit you as an input source

**Comment by ZeroDot1** [comment]
Thank you:)

**Comment by mitchellkrogza** [comment]
@ZeroDot1 readme updated 👍

**Comment by ZeroDot1** [comment]
👍👍👍👍👍👍👍👍👍
---
I update the list continuously, see: https://github.com/ZeroDot1/CoinBlockerLists/commits/master

**Comment by mitchellkrogza** [comment]
Great thanks for letting me know, I will add it as an auto update source. Please make sure that list.txt always remains a plain list like it is now and should also end with an empty newline.

**Comment by mitchellkrogza** [comment]
Added in https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/commit/d0453e8e8ce5899a31a285c066bd7b8a5b4967d8
