### ISSUE TITLE
appleid.apple.com 

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#91]
this still not working

**Comment by mitchellkrogza** [comment]
I’ll found out why tomorrow

**Comment by mitchellkrogza** [comment]
@xxcriticxx try now with latest update. There are some additional domains that appleid calls which are now whitelisted. Let me know.

**Comment by xxcriticxx** [comment]
looks like its working

**Comment by mitchellkrogza** [comment]
@xxcriticxx In future to see what is being blocked use the Google Chrome browser

click on View > Developer > Develop Tools
click on the Security Tab
Reload the page and any blocked domains will be reflected.

**Comment by xxcriticxx** [comment]
@mitchellkrogza i found this being blocked on my iphone

**Comment by xxcriticxx** [comment]
@mitchellkrogza whats the rest of domais?

**Comment by mitchellkrogza** [comment]
@xxcriticxx they are shown in this commit https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/commit/132ac85cded2b58726f2c82c8626406c995bef7d
