### ISSUE TITLE
instagram photos

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#92]
we blocking instagram photos with something 

https://www.mojanorwegia.pl/wydarzenia/trwa-norway-cup-najwiekszy-swiatowy-turniej-dla-dzieci-i-mlodziezy-z-calego-swiata-11721.html

![screenshot from 2017-10-26 21-03-38](https://user-images.githubusercontent.com/15007183/32083530-32156fdc-ba91-11e7-9f9a-0a083d39aeed.png)

**Comment by xxcriticxx** [comment]
::: /etc/pihole/list.41.hosts.ubuntu101.co.za.domains (1 results)
0.0.0.0 platform.instagram.com

**Comment by mitchellkrogza** [comment]
@xxcriticxx please try now with latest update.
