### ISSUE TITLE
playstation.com

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#95]
::: /etc/pihole/list.41.hosts.ubuntu101.co.za.domains (1 results)
0.0.0.0 playstation.com

**Comment by xxcriticxx** [comment]
@mitchellkrogza did you forget about this repo?

**Comment by mitchellkrogza** [comment]
Hi @xxcriticxx no just been ill for past 8-9 days but on the mend. Update / fixes on these issues today.
