### ISSUE TITLE
footprint.net

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#99]
::: /etc/pihole/list.41.hosts.ubuntu101.co.za.domains (1 results)
0.0.0.0 footprint.net

example:

i think this some kind of metric system (i can whitelist this only on my system if you want)

`scripps-hgtv-live-sonytv-i.secure.footprint.net`

**Comment by mitchellkrogza** [comment]
Seems to belong to MarkMonitor https://who.is/whois/footprint.net

**Comment by xxcriticxx** [comment]
np i will whitelist locally

**Comment by mitchellkrogza** [comment]
Some googling reveals that Apple also uses them? Need to look into it a bit more

**Comment by xxcriticxx** [comment]
out of 40 something lists i have in my pie only you block it and 1 more list looks good to me
